CREATE SCHEMA IF NOT EXISTS MY_SCHEMA;

CREATE TABLE MY_SCHEMA.MY_TABLE (
    X__ID VARCHAR2(30),
    X__INSDATE DATE DEFAULT SYSDATE ,
    X__INSUSER VARCHAR2(30) DEFAULT '0' ,
    X__MODDATE DATE,
    X__MODUSER VARCHAR2(30),
    X__VERSION NUMBER DEFAULT 0 ,
    CONSTRAINT PK_MY_TABLE PRIMARY KEY (X__ID),
    CONSTRAINT CC_MY_TABLE_ID CHECK ("X__ID" IS NOT NULL),
    CONSTRAINT CC_MY_TABLE_INSDATE CHECK ("X__INSDATE" IS NOT NULL),
    CONSTRAINT CC_MY_TABLE_INSUSER CHECK ("X__INSUSER" IS NOT NULL),
    CONSTRAINT CC_MY_TABLE_VERSION CHECK ("X__VERSION" IS NOT NULL)
);

CREATE UNIQUE INDEX PK_MY_TABLE ON MY_SCHEMA.MY_TABLE (X__ID);
