= 0.4.0 -> 0.5.0

== Changes

=== General
coff:ee upgrade 1.5.0 → 1.6.0

=== roaster-restassured
* Injectable ResponseProcessor configurable from Microprofile Config (`@RestProcessor`, `ConfigurableResponseProcessor`)
* The `testOpenAPI` method in the OpenAPITestHelper class has been enhanced with an `expectedOpenapiVersion` parameter to allow project-wide configuration.
With overloading, the original syntax is preserved, calling it defaults to 3.0.3, which is the expected openapi version.
* Two overrideable methods `decorateRequestSpecification` and `decorateValidatableResponse` have been introduced in the OpenAPITestHelper class.
By default, the class handles logging for requests and responses. Logging can be disabled or configured at the project level by subclassing the class.
+
[source,java]
.Example of disabling response logging
----
@Model
@Alternative
@Priority(Interceptor.Priority.APPLICATION + 10)
public class ProjectOpenApiTestHelper extends OpenAPITestHelper {

    @Override
    protected ValidatableResponse decorateValidatableResponse(ValidatableResponse validatableResponse) {
//      return validatableResponse.log().all();
        return validatableResponse;
    }
}
----

=== Migration
* In `OpenAPITestHelper.testOpenAPI(java.lang.String)`, assertions are now run against `3.0.3` OpenAPI version instead of `3.0.1`.
If this does not meet the project requirements, the `OpenAPITestHelper.testOpenAPI(java.lang.String, java.lang.String)` method can be used to override the expected version.
+
[source,java]
.Example of disabling response logging
----
    @Test
    @DisplayName("Testing Sampple service /openapi")
    void testOpenapi() {
//    Default openapi test expected openapi version = 3.0.3
//    openAPITestHelper.testOpenAPI(projectSampleServiceBaseUri);
//    Openapi test with custom openapi version
      openAPITestHelper.testOpenAPI(projectSampleServiceBaseUri, "3.0.0");
    }
----