= 0.1.0 -> 0.2.0

== What's new

<<modules/modules-tm4j.adoc,TM4J - Test Management for Jira Modul>>

<<modules/modules-selenide.adoc,Selenide Modul>>

<<modules/modules-hibernate.adoc,Hibernate Modul>>

== Changes
=== roaster-restassured
* The default JSON object mapper now serializes time values to ISO format instead of the previous "1600871093.907000000"

* The deprecated option has been removed

[source,java]
----
@Inject
private RestAssuredConfig restAssuredConfig;
----

From now on, it can only be used with the @JSON qualifier

[source,java]
----
@Inject
@JSON
private RestAssuredConfig restAssuredConfig;
----

* The Weld container runs in enableDiscovery() mode, so it is not necessary to add classes separately
* hu.icellmobilsoft.roaster.restassured.BaseConfigurableWeldIT.configureWeld() has been deprecated

=== Migration

From the IT tests, manually added beans need to be removed, otherwise a "Bean name is ambiguous." error message will be received
[source,java]
----
@Deprecated
@Override
protected void configureWeld(Weld weld) {
    weld.addBeanClasses(SampleAction.class);
}
----

=== roaster-weldunit

* The Weld container runs in enableDiscovery() mode, so it is not necessary to add classes separately
* hu.icellmobilsoft.roaster.restassured.BaseConfigurableWeldIT.configureWeld() has been deprecated

=== Migration

In the unit tests, manually added beans need to be removed; otherwise, you will receive a "Bean name is ambiguous." error message
[source,java]
----
@Deprecated
@Override
protected void configureWeld(Weld weld) {
    weld.addBeanClasses(SampleAction.class);
}
----