= 0.5.0 -> 0.6.0

== Changes

=== General

==== BOM version upgrades
* coff:ee 1.6.0 → 1.8.0
* microprofile 3.3 -> 4.0
* smallrye-config 1.8.5 -> 2.0.2

==== Migration
The changes do not require any migration work and are backwards compatible

=== roaster-restassured
* The ResponseProcessor has been enhanced with the `deleteXml` and `deleteJson` methods

=== Migration
The changes do not require any migration work and are backwards compatible

=== roaster-selenide
* Selenide upgrade 5.22.2 -> 6.1.2

=== Migration
* The Selenide upgrade may cause issues. See: https://github.com/selenide/selenide/blob/master/CHANGELOG.md[Selenide changelog]

=== roaster-selenide-angular
* The module has been created, including the following components: `MatCheckbox`, `MatRadioGroup`, `MatSelect`, `MatSlideToggle`

=== Migration
The changes do not require any migration work and are backwards compatible

==== roaster-mongodb
* The module has been created

==== Migration
The changes do not require any migration work and are backwards compatible

==== roaster-oracle
* DB connection pool was introduced; the `maximumPoolSize` config key was created

==== Migration
The changes do not require any migration work and are backwards compatible
