= 2.5.0 -> 2.6.0

== What's new

=== Dependencies

* JUnit upgraded from `5.9.1` to `5.13.4`. Changes:
** https://docs.junit.org/5.10.0/release-notes/[JUnit 5.10.0]
** https://docs.junit.org/5.11.0/release-notes/[JUnit 5.11.0]
*** https://docs.junit.org/current/user-guide/#writing-tests-built-in-extensions-AutoClose[@AutoClose] annotation to automatically close field resources in tests
** https://docs.junit.org/5.12.0/release-notes/[JUnit 5.12.0]
** https://docs.junit.org/5.13.0/release-notes/[JUnit 5.13.0]
* Testcontainers upgraded from `1.17.6` to `1.21.3`.
See: https://github.com/testcontainers/testcontainers-java/releases/tag/1.18.0[1.18.0],
https://github.com/testcontainers/testcontainers-java/releases/tag/1.19.0[1.19.0],
https://github.com/testcontainers/testcontainers-java/releases/tag/1.20.0[1.20.0],
https://github.com/testcontainers/testcontainers-java/releases/tag/1.21.0[1.21.0]
* Mockito upgraded from `4.10.0` to https://github.com/mockito/mockito/releases/tag/v4.11.0[4.11.0]
(It's the newest version in the 4.x.x branch, but not the newest overall)
* Weld-junit upgraded from `4.0.0.Final` to https://github.com/weld/weld-testing/releases/tag/4.0.5.Final[4.0.5.Final] to support newer JUnit versions. See: https://github.com/weld/weld-testing/pull/266

==== Migration

If you get a `Unable to load proxy class for bean Implicit Bean` exception in weld tests you should open the `java.base` module:
[source,xml]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <argLine>--add-opens=java.base/java.lang=ALL-UNNAMED</argLine>
    </configuration>
</plugin>
----

=== roaster-jaxrs/roaster-restassured

* The `RestProcessor` qualifier search is replaced in `AbstractConfigurableResponseProcessorProducer`.

==== Migration

Changes are backwards compatible, doesn't need any migration.

=== roaster-hibernate

* The hibernate module was split into two variants: hibernate-cdi and hibernate-se. The CDI one contains the old functionality,
the SE one is new, which can be used without a CDI container.

==== Migration

For minimal migration in every `pom.xml` the artifactId should be replaced from `roaster-hibernate` to `roaster-hibernate-cdi`.
The imports should be the same.

For full migration the `roaster-hibernate` artifactId should be `roaster-hibernate-se`.
After that the imports should be replaced from

`import hu.icellmobilsoft.roaster.hibernate.annotation.HibernatePersistenceConfig;`

to

`import hu.icellmobilsoft.roaster.hibernate.se.EntityManagerCache;`

And the `EntityManager` fields should be transformed with the following regex replace:

[source,java]
----
    @Inject
    @HibernatePersistenceConfig\(persistenceUnitName = ([^)]+)\)
    ((?:private )|(?:protected )|(?:public ))?EntityManager (.+);
----

to:

[source,java]
----
    $2EntityManager $3 = EntityManagerCache.getForPersistenceUnit($1);
----

=== roaster-jaxrs

* The hibernate module was split into two variants: roaster-jaxrs-cdi and roaster-jaxrs-se. The CDI one contains the old functionality,
the SE one is new, which can be used without a CDI container.

==== Migration

For minimal migration in every `pom.xml` the artifactId should be replaced from `roaster-jaxrs` to `roaster-jaxrs-cdi`.
And replace the following imports:

* `hu.icellmobilsoft.roaster.jaxrs.response.ResponseProcessor`
to `hu.icellmobilsoft.roaster.jaxrs.se.response.ResponseProcessor`
* `hu.icellmobilsoft.roaster.jaxrs.response.producer.ResponseProcessorConfig`
to `hu.icellmobilsoft.roaster.jaxrs.se.response.ResponseProcessorConfig`
* `hu.icellmobilsoft.roaster.jaxrs.response.producer.spi.AbstractConfigurableResponseProcessor`
to `hu.icellmobilsoft.roaster.jaxrs.se.ConfigurableResponseProcessor`

Also, you have to replace the following codes:

* `extends AbstractConfigurableResponseProcessor` to `extends ConfigurableResponseProcessor`

For full migration the `roaster-jaxrs` artifactId should be `roaster-jaxrs-se`.
After that the `ConfigurableResponseProcessor` fields should be transformed with the following regex replace:

[source,java]
----
    @Inject
    @RestProcessor\(configKey = "([^"]+)"\)
    ((?:private )|(?:protected )|(?:public ))?ConfigurableResponseProcessor<([^\)]+)> (.+);
----

to:

[source,java]
----
    $2ConfigurableResponseProcessor<$3> $4 = hu.icellmobilsoft.roaster.jaxrs.se.response.ConfigurableResponseProcessorFactory
            .create("$1");
----

and

[source,java]
----
    @Inject
    @RestProcessor\(configKey = "([^"]+)", expectedStatusCode = ([^\)]+)\)
    ((?:private )|(?:protected )|(?:public ))?ConfigurableResponseProcessor<([^\)]+)> (.+);
----
to:
[source,java]
----
    $3ConfigurableResponseProcessor<$4> $5 = hu.icellmobilsoft.roaster.jaxrs.se.response.ConfigurableResponseProcessorFactory
            .create("$1", $2);
----

=== roaster-restassured

* The hibernate module was split into two variants: roaster-restassured-cdi and roaster-restassured-se. The CDI one contains the old functionality,
the SE one is new, which can be used without a CDI container.

==== Migration

For minimal migration in every `pom.xml` the artifactId should be replaced from `roaster-restassured` to `roaster-restassured-cdi`.
And replace the following imports:

* `hu.icellmobilsoft.roaster.restassured.response.ResponseProcessor`
to `hu.icellmobilsoft.roaster.restassured.se.response.ResponseProcessor`
* `hu.icellmobilsoft.roaster.restassured.response.producer.spi.AbstractConfigurableResponseProcessor`
to `hu.icellmobilsoft.roaster.restassured.se.response.ConfigurableResponseProcessor`

Also, you have to replace the following codes:

* `extends AbstractConfigurableResponseProcessor` to `extends ConfigurableResponseProcessor`

For full migration the `roaster-restassured` artifactId should be `roaster-restassured-se`.
After that the `ConfigurableResponseProcessor` fields should be transformed with the following regex replace:

[source,java]
----
    @Inject
    @RestProcessor\(configKey = "([^"]+)"\)
    ((?:private )|(?:protected )|(?:public ))?ConfigurableResponseProcessor<([^\)]+)> (.+);
----
to:
[source,java]
----
    $2ConfigurableResponseProcessor<$3> $4 = hu.icellmobilsoft.roaster.restassured.se.response.ConfigurableResponseProcessorFactory
            .create("$1");
----

and

[source,java]
----
    @Inject
    @RestProcessor\(configKey = "([^"]+)", expectedStatusCode = ([^\)]+)\)
    ((?:private )|(?:protected )|(?:public ))?ConfigurableResponseProcessor<([^\)]+)> (.+);
----
to:
[source,java]
----
    $3ConfigurableResponseProcessor<$4> $5 = hu.icellmobilsoft.roaster.restassured.se.response.ConfigurableResponseProcessorFactory
            .create("$1", $2);
----
