= 0.7.0 -> 0.8.0

== Újdonságok

Létrejött egy új modul: *roaster-jaxrs*.
A fő célja hogy JAXRS szintú specifikációt használva megoldásokat nyújcson olyan igényekre,
melyek a *roaster-restassured* nem tud.
Ilyen például a multipart kezelés,
vagy a microprofile-rest-client lehetősége,
ami sok customizálást tud pótolni.
A *roaster-jaxrs* modulhoz készült leírás <<Jaxrs>> és testsuite is.

== Változások

=== Általános
* hu.icellmobilsoft.roaster.common.util.FileUtil kiegészült `InputStream` olvasó paraméterekkel,
hibakezelést megoldja maga a funkció.

==== BOM verzió emelések
* coffee v1.8.0 -> https://i-cell-mobilsoft-open-source.github.io/coffee/#_v1_9_0_v1_10_0[v1.10.1]
* deltaspike 1.9.1 -> 1.9.6 

=== roaster-restassured
* A `HealthCheckTestHelper` módosult, a továbbiakban az általános `/health` végpont hívás mellett lehetőség van a tipizált probe hivásokat használni:
- `/health/ready`
- `/health/live`
- `/health/started`
* Az új *roaster-jaxrs* modul dependencia-ként lett bekötve,
mivel a konfigurációjuk és a használatuk közös (azonos osztályok).
Ez okoz apró változásokat a java path elérésében.

=== Átállás
A változtatás igényel apró változásokat,
mégpedig a következő java path-ok változtak:

* hu.icellmobilsoft.roaster.*restassured*.response.producer.ManagedResponseProcessorConfig -> hu.icellmobilsoft.roaster.*jaxrs*.response.producer.ManagedResponseProcessorConfig
* hu.icellmobilsoft.roaster.*restassured*.response.producer.ResponseProcessorConfig -> hu.icellmobilsoft.roaster.*jaxrs*.response.producer.ResponseProcessorConfig
* hu.icellmobilsoft.roaster.*restassured*.response.producer.RestProcessor -> hu.icellmobilsoft.roaster.*jaxrs*.response.producer.RestProcessor

Egyébként nincs semmi működési változás, minden más érintettlen, visszafelé kompatibilis.

=== roaster-redis
A Coff:ee frissítése változást okozott a `hu.icellmobilsoft.roaster.redis.RedisHandler`
osztályban (coffee-ban kivezetésre került a `RedisService`).
Apró változásokat okozott az átvezetés,
és mégpedig hogy a metódusok visszatérése `Optional` értékkel jön az eddigi `String` vagy `void` helyett.

=== Átállás
A változtatás apró korrekciókat igényelhet a visszatérési értekek típusánál,
egyébként visszafelé kompatibilis.
