= 0.2.0 -> 0.3.0

== Változások

=== Általános
coff:ee frissítés 1.2.1 → 1.3.0

=== roaster-hibernate
Az `EntityManagerProducer` osztályban az `EntityManagerFactory` injectálás törlésre került és a
`produceDefaultEntityManager()` metódus magában állítja elő, amikor szükség van rá.
Így mostantól már csak akkor jön létre alapértelmezett beállításokkal `EntityManagerFactory`,
ha `@HibernatePersistenceConfig` annotáció nélkül injectálunk `EntityManager`-t.

=== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

=== roaster-tm4j
* Bugfix: Több teszt maven futtatása során már nem jön exception
* Bugfix: TM4J `Executed by` értékét újra töltik a tesztek
* TM4J environment értékét töltik a tesztek config paraméter alapján

=== Átállás
* A tesztosztályt (vagy ősét) fel kell annotálni a következővel: `@TestInstance(TestInstance.Lifecycle.PER_CLASS)`
* `roaster.tm4j.environment` config paraméterben megadott értéket létre kell hozni TM4J felületen amennyiben nem létezik