= 2.0.0 -> 2.1.0

== Changes

=== General

==== BOM version upgrades:
* Bump com.google.guava:guava https://github.com/google/guava/releases/tag/v31.1[31.1-jre]
-> https://github.com/google/guava/releases/tag/v32.1.1[32.1.1-jre]
(https://github.com/advisories/GHSA-7g45-4rm6-3mm3[CVE-2023-2976])
* com.codeborne:selenide: 6.10.3 -> 6.18.0

=== Hibernate

* The configuration values related to logging and statistics generation that are burned in the `EntityManagerFactoryProducer` class are now loaded from the roaster configuration file: `LOG_SESSION_METRICS`, `LOG_JDBC_WARNINGS`, `GENERATE_STATISTICS`.

=== Migration

* The configuration keys `LOG_SESSION_METRICS`, `LOG_JDBC_WARNINGS`, and `GENERATE_STATISTICS` are set to `false` instead of the previous default `true` if they are not included in the configuration file. 
Therefore, if we want to enable these, it is necessary to add them to the configuration file and set them to `true`.

=== roaster-tm4j/roaster-testsuite-tm4j

Bug fix due to Jakarta, dependency upgrade

* hu.icellmobilsoft.roaster.testsuite.tm4j.Tm4jIT
* hu.icellmobilsoft.roaster.testsuite.tm4j.Tm4jTagCycleIT

=== roaster-zephyr

Bug fix due to Jakarta, dependency upgrade

* hu.icellmobilsoft.roaster.testsuite.zephyr.ZephyrIT
* hu.icellmobilsoft.roaster.testsuite.zephyr.ZephyrTagCycleIT

==  roaster-selenide

"Due to an update in the Selenide version, the `driverManagerEnabled` switching option has been removed."
