== 0.4.0 -> 0.5.0

=== Változások

==== Általános
coff:ee frissítés 1.5.0 → 1.6.0

==== roaster-restassured
* Microprofile konfigból állítható injektálható ResponseProcessor (`@RestProcessor`, `ConfigurableResponseProcessor`)
* Az OpenAPITestHelper osztály `testOpenAPI` metódusa kiegészült `expectedOpenapiVersion` paraméterrel, hogy projekt szinten lehessen állítani.
Túlterheléssel megmaradt az eredeti szintaxis is, ezt hívva alapértelmezetten `3.0.3` az elvárt openapi verzió.
* Az OpenAPITestHelper osztályba bevezetésre került két felülírható metódus `decorateRequestSpecification`, `decorateValidatableResponse`.
Default működés esetén request és response logolást intézi, projekt szinten kikapcsolható/konfigurálható a logolás az osztály leszármaztatásával.
+
[source,java]
.Példa response log kikapcsolásra
----
@Model
@Alternative
@Priority(Interceptor.Priority.APPLICATION + 10)
public class ProjectOpenApiTestHelper extends OpenAPITestHelper {

    @Override
    protected ValidatableResponse decorateValidatableResponse(ValidatableResponse validatableResponse) {
//      return validatableResponse.log().all();
        return validatableResponse;
    }
}
----

==== Átállás
* `OpenAPITestHelper.testOpenAPI(java.lang.String)` a továbbiakban `3.0.1` helyett `3.0.3` OpenAPI verzióra futtat assertet.
Amennyiben ez projekt szinten nem felel meg a `OpenAPITestHelper.testOpenAPI(java.lang.String, java.lang.String)` metódussal felülírható az elvárt verzió.
+
[source,java]
.Példa response log kikapcsolásra
----
    @Test
    @DisplayName("Testing Sampple service /openapi")
    void testOpenapi() {
//    Default openapi test expected openapi version = 3.0.3
//    openAPITestHelper.testOpenAPI(projectSampleServiceBaseUri);
//    Openapi test with custom openapi version
      openAPITestHelper.testOpenAPI(projectSampleServiceBaseUri, "3.0.0");
    }
----
