= 0.2.0 -> 0.3.0

== Changes

=== General
coff:ee upgrade 1.2.1 → 1.3.0

=== roaster-hibernate
In the `EntityManagerProducer` class, injection of `EntityManagerFactory` has been removed, and the `produceDefaultEntityManager()` method now creates it internally when needed
So from now on, the `EntityManagerFactory` with default settings is only created when injecting `EntityManager` without the `@HibernatePersistenceConfig` annotation

=== Migration
The changes do not require any migration work and are backwards compatible

=== roaster-tm4j
* Bugfix: Running more test maven no longer cause exception
* Bugfix: TM4J `Executed by` value is reloaded by the tests
* They load the TM4J environment value based on the test configuration parameter

=== Migration
* The test class (or its superclass) must be annotated with `@TestInstance(TestInstance.Lifecycle.PER_CLASS)`
* The value provided in the `roaster.tm4j.environment` configuration parameter must be created in the TM4J interface if it does not exist