[#modules-zephyr]
= Zephyr Scale Cloud

The purpose of this module is to automatically report the results of automated test cases to a Zephyr Scale Cloud environment on a JIRA interface running in the cloud.

== Configuration

[source,yaml]
.META-INF/roaster-defaults.yml
----
roaster:
   zephyr:
      enabled: true #<1>
      projectKey: ABC #<2>
      testCycleKey: ABC-C1 #<3>
      environment: sandbox #<4>
      server/mp-rest/url: https://jira.example.com #<5>
      server/authToken: ZXhhbXBsZS11c2VyOnNlY3JldA== #<6>
      server/email: tim@examplemail.com #<7>
      server/apiToken: dGltQGV4YW1wbGVtYWlsLmNvbTpteUFwaUtleQ== #<8>
      cloud/bearerToken: jwtBearerToken #<9>
      cycle:
         foo: ABC-C2 #<10>
         bar: ABC-C3
----
<1> The Zephyr server call can be disabled with this flag (default: false).
<2> Jira project key. It is usually the prefix of Jira issues.
<3> Zephyr test cycle key. For example, ABC-C1 where ABC is the project key.
<4> (Optional) The name of the current environment where the tests are running. (Needs to be created in Jira)
<5> Remote Jira server URL.
<6> base64(email + ":" + apiToken)
<7> Email address associated with the Jira user. This user should be used to generate the apiToken and bearerToken.
<8> ApiToken for using remote Jira functionalities. It needs to be generated in the Jira profile interface.
<9> Zephyr Scale Bearer Token. It needs to be generated on the remote Jira interface, in your own profile section.
<10> Possibility to specify different Zephyr test cycles per test tag.
If a test is tagged with a tag that is listed here (e.g., `@Tag("foo")` in JUnit 5), the result will be reported to the specified cycle instead of the default test cycle (testCycleKey configuration key).
If a test has multiple tags, the result will be reported to each corresponding cycle.

For more detailed information on generating tokens, please refer to the following links:

[Manage Api Tokens for your Atlassian Account](https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/)

[Generating API Access Tokens (Bearer Token)](https://support.smartbear.com/zephyr-scale-cloud/docs/rest-api/generating-api-access-tokens.html)

[TIP]
For security reasons, it is recommended not to include the authToken and api tokens directly in the configuration file. Instead, you can pass them as command-line arguments to Maven.
For example: `$ mvn test -Droaster.zephyr.server/authToken=secret`

== Usage with JUnit 5

To use the module, you need to add the following Maven dependency to your pom.xml:

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-zephyr-junit5</artifactId>
</dependency>
----

After that, you just need to annotate the test classes/methods that you want to report the results of:

[source,java]
----
@ExtendWith(ZephyrExtension.class) // Activate the Zephyr extension on the test class
@TestInstance(Test

Instance.Lifecycle.PER_CLASS)
class ExampleTest extends BaseWeldUnitType {
    @Test
    @TestCaseId("ABC-T1") // Link the test case to Zephyr
    void testOne() {
        assertTrue(1 + 1 == 2);
    }
}
----