= RestAssured

To use the RestAssured module, you only need to reference it in the pom.xml file.

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-restassured</artifactId>
</dependency>
----

== Using RestAssured

The test files follow the following pattern:

[source,java]
----
@DisplayName("Testing XY service hu.icellmobilsoft.project.sample.service.rest.test.ISampleTestRest.postSampleRquest")
@Tag(TestSuiteGroup.RESTASSURED)
public class PostSampleRequestIT extends BaseConfigurableWeldIT {

    @Inject
    @ConfigProperty(name = "service.sample.uri")
    private String baseUri;

    @Inject
    @JSON
    private RequestSpecification requestSpecification;

    @Inject
    @JSON
    private ResponseSpecification responseSpecification;

    @ParameterizedTest
    @CsvSource({ "1, 1, 2", "2, 3, 5", })
    @ExplicitParamInjection
    void test(int a, int b, int expectedSum) {
      Assertions.assertEquals(expectedSum, a + b);
    }

    @Test
    @DisplayName("Testing opg generator json rest")
    void testSampleRest() {
        SampleRequest body = new SampleRequest();

        SampleResponse actual = RestAssured
                // given
                .given()//
                .spec(requestSpecification)//
                .config(restAssuredConfig).body(body) //
                .baseUri(baseUri) //
                // when
                .when()//
                .log().all()//
                .post("/sample")
                // then
                .then()//
                .log().all()//
                .spec(responseSpecification)//
                .extract().response().getBody().as(SampleResponse.class);
        Assertions.assertEquals(FunctionCodeType.OK, actual.getFuncCode());
    }
}
----

=== RestAssured default configurations

By default, the system supports XML or JSON formats.
The settings are handled by the following classes:

* RestAssuredConfigProducer
* RequestSpecificationProducer
* ResponseSpecificationProducer

These classes can be freely modified in the implementing project.

==== JSON default configurations

* The request content-type and accept are set to "application/json".
* The response expects an HTTP status of 200 and "application/json" accept.
* The default settings are summarized in Jackson2ObjectMapperFactoryImpl.

If you need a custom ObjectMapperConfig, similar to the one created in ObjectMapperConfigProducer,
you can use the following example:

[source,java]
----
@Inject
@JSON
private RestAssuredConfig restAssuredConfig;
 
((Jackson2ObjectMapperFactoryImpl) restAssuredConfig.getObjectMapperConfig().jackson2ObjectMapperFactory()).getObjectMapper()
        .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
----

==== XML default configurations

* Encoding is set to UTF-8.
* The request content-type and accept are set to "application/xml".
* The response expects an HTTP status of 200 and "application/xml" accept.


=== ResponseProcessor

==== Implementation

The `ResponseProcessor` abstract class was created to assist in testing a specific endpoint.
When inheriting from it, you need to specify the response type as a generic parameter
and implement two methods that return a String to identify the endpoint:

* `baseUriKey`: The key used in Roaster configuration that specifies the endpoint's baseUri.
* `path`: The endpoint path. For example, in the case of http://localhost/foo/bar, it would be: /foo/bar

Optionally, other methods of the class can be overridden to customize request or response processing.
For example, by overriding the `createRequestSpecification` method, you can modify request headers, cookies, etc.

==== Usage

Using the `getJson`, `postJson`, `getXml`, and `postXml` methods of the `ResponseProcessor` implementation,
you can invoke the endpoint and automatically parse

 the response.

==== Example

[source,java]
----
public class ExampleQueryResponseProcessor extends ResponseProcessor<ExampleQueryResponse> {

    @Override
    public String baseUriKey() {
        return "example-project.example-service.url"; // example value: http://localhost:8080
    }

    @Override
    public String path() {
        return "/example/foo/{id}";
    }

    @Override // Example of adding an extra header
    protected RequestSpecification createRequestSpecification(RequestSpecification initRequestSpecification) {
        return super.createRequestSpecification(initRequestSpecification)
                .header("Authorization", "Basic dXNlcjpwYXNz");
    }

    public ExampleQueryResponse queryWithJson(String id) {
        return getJson(ExampleQueryResponse.class, id);
    }

    public ExampleQueryResponse queryWithXml(String id) {
        return getXml(ExampleQueryResponse.class, id);
    }
}
----

=== ConfigurableResponseProcessor

To avoid implementing a separate `ResponseProcessor` for each REST endpoint,
the `ConfigurableResponseProcessor` class was created, which reads the necessary values from configuration,
such as `baseUriKey` and `path`.

==== Usage

The `baseUriKey` and `path` should be added under a common prefix in the configuration.
Optionally, headers can also be specified.
In YAML format, it would look like this:

[source,yml]
----
testsuite:
    rest:
        exampleService:
            example:
                baseUriKey: example-project.example-service.url
                path: /rest/exampleService/example/{id}
            headerExample:
                baseUriKey: example-project.example-service.url
                path: /rest/exampleService/example/{id}
                headers:
                    - "X-LANGUAGE: hu"
                    - "User-Agent: roaster/0.5 restassured"
----

In the test class, the `ConfigurableResponseProcessor` can be injected using the `@RestProcessor` qualifier,
providing the configuration prefix:

[source,java]
----
import hu.icellmobilsoft.roaster.restassured.response.producer.impl.ConfigurableResponseProcessor;

class ExampleTest {
    @Inject
    @RestProcessor(configKey = "testsuite.rest.exampleService.example") //<1>
    private ConfigurableResponseProcessor<ExampleResponse> responseProcessor;

    @Inject
    @RestProcessor(
            configKey = "testsuite.rest.exampleService.example",
            expectedStatusCode = HttpStatus.SC_BAD_REQUEST //<2>
    )
    private ConfigurableResponseProcessor<ExampleResponse> badRequestResponseProcessor;

    void test() {
        responseProcessor.setQueryParams(Map.of("foo", "42")); //<3>
        ExampleResponse response = responseProcessor.getJson(ExampleResponse.class, "XXX");
        // asserts...
    }
}
----
<1> Example of injecting the default `ConfigurableResponseProcessor`
<2> Optionally, the expected response status code can be provided in the annotation (default: `200 OK`)
<3> Query parameters can be set in the `ConfigurableResponseProcessor`

==== Custom implementation

If you want to extend the behavior of `ConfigurableResponseProcessor` within the project
(e.g., for login or other project-specific header handling),
you can start by implementing the `AbstractConfigurableResponseProcessor`:

[source,java]
----
import hu.icellmobilsoft.roaster.restassured.response.producer.spi.AbstractConfigurableResponseProcessor;

@Dependent
public class LoginConfigurableResponseProcessor<RESPONSE> extends AbstractConfigurableResponseProcessor<RESPONSE> {
    @Inject
    private LoginHandler loginHandler;

    @Override
    protected RequestSpecification createRequestSpecification(RequestSpecification initRequestSpecification) {
        loginHandler.login();
        return super.createRequestSpecification(initRequestSpecification)


                .headers(loginHandler.loginHeaders());
    }
}
----

Next, you need to create a CDI producer that serves the configured instances:

[source,java]
----
import hu.icellmobilsoft.roaster.restassured.response.producer.spi.AbstractConfigurableResponseProcessorProducer;

@Dependent
public class LoginConfigurableResponseProcessorProducer<RESPONSE> extends AbstractConfigurableResponseProcessorProducer<LoginConfigurableResponseProcessor<RESPONSE>> {
    @Override
    @Produces //<1>
    @RestProcessor(configKey = "")
    public LoginConfigurableResponseProcessor<RESPONSE> createLoginResponseProcessor(InjectionPoint injectionPoint) {
        return super.createConfiguredResponseProcessor(injectionPoint);
    }

    @Override
    protected LoginConfigurableResponseProcessor<RESPONSE> getBaseResponseProcessor() { //<2>
        return CDI.current().select(LoginConfigurableResponseProcessor.class).get();
    }
}
----
<1> A producer needs to be created (calling `getConfiguredResponseProcessor` will give you a pre-configured instance)
<2> Override `getBaseResponseProcessor` to return your own type (this is what `getConfiguredResponseProcessor` will configure)

After that, you can use your own implementation, together with the default solution, in a single test:

[source,java]
----
import hu.icellmobilsoft.roaster.restassured.response.producer.impl.ConfigurableResponseProcessor;

class ExampleTest {
    @Inject
    @RestProcessor(configKey = "testsuite.rest.exampleService.example")
    private LoginConfigurableResponseProcessor<ExampleResponse> loginResponseProcessor;

    @Inject
    @RestProcessor(
            configKey = "testsuite.rest.exampleService.example",
            expectedStatusCode = HttpStatus.SC_UNAUTHORIZED
    )
    private ConfigurableResponseProcessor<ExampleResponse> noLoginResponseProcessor;
}
----