= Maven structure

== Project repository

The tests can reside in the same repository as the project,
under a separate module named "testsuite" under the main pom.
It is recommended to put the "testsuite" node in an inactivable profile, for example:

.Main project pom.xml
[source,xml]
----
<profiles>
  <profile>
    <id>ci</id>
    <activation>
      <activeByDefault>true</activeByDefault>
    </activation>
    <modules>
      <module>project-testsuite</module>
    </modules>
  </profile>
</profiles>
----

[subs="quotes"]
.Recommended example project maven structure
----
project-backend
+-- project-bom
+-- project-common
+-- project-sample
\-- *project-testsuite*
----

== Testsuite module

Within the testsuite module, the child POMs follow the structure defined by the project.
So, if a service in the project is located under project-backend/project-sample/project-sample-service,
then the tests corresponding to this service will be placed under project-backend/project-testsuite/project-testsuite-sample/project-testsuite-sample-service POM.

We further divide the testsuite Maven module for the service into submodules according to the REST interfaces found in the service.
Each submodule will contain test classes corresponding to operations.

[subs="quotes"]
.Example testsuite module structure
----
*project-backend*
+-- *project-bom*
+-- *project-common*
+-- *project-sample*
|   \-- *project-sample-service*
|       \-- src/main/java/
|           \-- hu.icellmobilsoft.project.sample.service.rest
|               +-- IUserRest.java //<1>
|               |   +-- _postUser()_ //<2>
|               |   \-- _putUser()_ //<3>
|               \-- ISampleRest.java //<4>
|                   \-- _getSample()_ //<5>
\-- *project-testsuite*
    +-- *project-testsuite-common*
    \-- *project-testsuite-sample*
        \-- *project-testsuite-sample-service*
            +-- *project-testsuite-sample-service-user-rest* //<1>
                \-- src/test/java/
                    \-- hu.icellmobilsoft.project.testsuite.sample.service.rest
                        +-- _PostUserIT_ //<2>
                        \-- _PutUserIT_ //<3>
            \-- *project-testsuite-sample-service-sample-rest* //<4>
                \-- src/test/java/
                    \-- hu.icellmobilsoft.project.testsuite.sample.service.rest
                        \-- _GetSampleIT_ //<5>
----
<1> The `IUserRest` interface of the `sample-service`. It has a separate pom in the testsuite: `project-testsuite-sample-service-user-rest`
<2> The `IUserRest.postUser()` operation. In the testsuite, it has its own test class under the `user-rest` pom: `PostUserIT`
<3> The `IUserRest._putUser()` operation. In the testsuite, it has its own test class under the `user-rest` pom: `PutUserIT`
<4> The `ISampleRest` interface in the `sample-service`. It has its own pom in the testsuite: `project-testsuite-sample-service-sample-rest`
<5> `IUserRest.getSample()` operation. It has its own test class under the `sample-rest` pom in the testsuite: `GetSampleIT`.
