= Maven struktúra

== Project repository

A tesztek a projekttel egy repositoryba kerülhetnek,
a fő pom alatt külön testsuite modulba.
Érdemes a "testsuite" csomópontot inaktiválható profilba rakni, például:

.Fő projekt pom.xml
[source,xml]
----
<profiles>
  <profile>
    <id>ci</id>
    <activation>
      <activeByDefault>true</activeByDefault>
    </activation>
    <modules>
      <module>project-testsuite</module>
    </modules>
  </profile>
</profiles>
----

[subs="quotes"]
.Ajánlott példa project maven struktúra
----
project-backend
+-- project-bom
+-- project-common
+-- project-sample
\-- *project-testsuite*
----

== Testsuite module

A testsuite modulon belül a child pomok követik a projekt szerinti strukúrát.
Azaz ha pl. a projecten egy service a `project-backend/project-sample/project-sample-service` modulban található,
akkor a service-hez tartozó tesztek `project-backend/project-testsuite/project-testsuite-sample/project-testsuite-sample-service` pom alá kerülnek.

A service-hez tartozó testsuite maven module-t további almodulokra bontjuk a service-ben található REST interface-eknek megfelelően,
ezekbe az almodulokba kerülnek az operációnként külön teszt osztályok.

[subs="quotes"]
.Példa testsuite modul felépítése
----
*project-backend*
+-- *project-bom*
+-- *project-common*
+-- *project-sample*
|   \-- *project-sample-service*
|       \-- src/main/java/
|           \-- hu.icellmobilsoft.project.sample.service.rest
|               +-- IUserRest.java //<1>
|               |   +-- _postUser()_ //<2>
|               |   \-- _putUser()_ //<3>
|               \-- ISampleRest.java //<4>
|                   \-- _getSample()_ //<5>
\-- *project-testsuite*
    +-- *project-testsuite-common*
    \-- *project-testsuite-sample*
        \-- *project-testsuite-sample-service*
            +-- *project-testsuite-sample-service-user-rest* //<1>
                \-- src/test/java/
                    \-- hu.icellmobilsoft.project.testsuite.sample.service.rest
                        +-- _PostUserIT_ //<2>
                        \-- _PutUserIT_ //<3>
            \-- *project-testsuite-sample-service-sample-rest* //<4>
                \-- src/test/java/
                    \-- hu.icellmobilsoft.project.testsuite.sample.service.rest
                        \-- _GetSampleIT_ //<5>
----
<1> sample-service `IUserRest` interface-e. A testsuite-ban külön pom tartozik hozzá: `project-testsuite-sample-service-user-rest`
<2> `IUserRest.postUser()` operáció. Testsuite-ban a user-rest pom alatt saját tesztosztály tartozik hozzá: `PostUserIT`
<3> `IUserRest._putUser()` operáció. Testsuite-ban a user-rest pom alatt saját tesztosztály tartozik hozzá: `PutUserIT`
<4> sample-service `ISampleRest` interface-e. A testsuite-ban külön pom tartozik hozzá: `project-testsuite-sample-service-sample-rest`
<5> `IUserRest._getSample()` operáció. Testsuite-ban a sample-rest pom alatt saját tesztosztály tartozik hozzá: `GetSampleIT`
