= Migrációs leírás

Következő szekció a verzió kiadások közötti változásokat írja le.

== 0.1.0 -> 0.2.0

=== Újdonságok

<<modules/modules-tm4j.adoc,TM4J - Test Management for Jira Modul>>

<<modules/modules-selenide.adoc,Selenide Modul>>

<<modules/modules-hibernate.adoc,Hibernate Modul>>

=== Változások
==== roaster-restassured
* A default JSON object mapper az idő értékeket ISO formátumra serializálja az eddigi "1600871093.907000000" helyett.

* Megszünt a deprecated lehetőség 

[source,java]
----
@Inject
private RestAssuredConfig restAssuredConfig;
----

Ezentúl már csak @JSON qualifier-el lehet használni

[source,java]
----
@Inject
@JSON
private RestAssuredConfig restAssuredConfig;
----

* Weld konténer enableDiscovery() módban fut, nem szükséges külön hozzáadni az osztályokat.
* hu.icellmobilsoft.roaster.restassured.BaseConfigurableWeldIT.configureWeld() depreceted lett.

==== Átállás

Az IT tesztekből ki kell venni az eddig manualisan hozzáadott bean-eket, egyébként 
"Bean name is ambiguous." hibaüzenetet kapunk.
[source,java]
----
@Deprecated
@Override
protected void configureWeld(Weld weld) {
    weld.addBeanClasses(SampleAction.class);
}
----

==== roaster-weldunit

* Weld konténer enableDiscovery() módban fut, nem szükséges külön hozzáadni az osztályokat.
* hu.icellmobilsoft.roaster.weldunit.BaseWeldUnitType.configureWeld() depreceted lett.

==== Átállás

A unit tesztekből ki kell venni az eddig manualisan hozzáadott bean-eket, egyébként 
"Bean name is ambiguous." hibaüzenetet kapunk.
[source,java]
----
@Deprecated
@Override
protected void configureWeld(Weld weld) {
    weld.addBeanClasses(SampleAction.class);
}
----

== 0.2.0 -> 0.3.0

=== Változások

==== Általános
coff:ee frissítés 1.2.1 → 1.3.0

==== roaster-hibernate
Az `EntityManagerProducer` osztályban az `EntityManagerFactory` injectálás törlésre került és a
`produceDefaultEntityManager()` metódus magában állítja elő, amikor szükség van rá.
Így mostantól már csak akkor jön létre alapértelmezett beállításokkal `EntityManagerFactory`,
ha `@HibernatePersistenceConfig` annotáció nélkül injectálunk `EntityManager`-t.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

==== roaster-tm4j
* Bugfix: Több teszt maven futtatása során már nem jön exception
* Bugfix: TM4J `Executed by` értékét újra töltik a tesztek
* TM4J environment értékét töltik a tesztek config paraméter alapján

==== Átállás
* A tesztosztályt (vagy ősét) fel kell annotálni a következővel: `@TestInstance(TestInstance.Lifecycle.PER_CLASS)`
* `roaster.tm4j.environment` config paraméterben megadott értéket létre kell hozni TM4J felületen amennyiben nem létezik

== 0.3.0 -> 0.4.0

=== Változások

==== Általános
coff:ee frissítés 1.3.0 → 1.5.0

==== roaster-tm4j
* Bugfix: TM4J `Executed by` értékét töltésére a `userKey`-t használjuk a `userName` helyett.

==== roaster-restassured
* A ResponseProcessor kiegészült a putXml, és putJson metódusokkal

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

==== roaster-api
* A FileUtil átkerült az újonnan létrehozott roaster-common-util-ba.

==== Átállás
A FileUtil-t érintő dependency és package változásokat szükséges átvezetni.

==== roaster-selenide
* Bugfix: Konfigurációs paraméter felolvasásának javitása: headless browser run
* Selenide verzió frissítés 5.15.0 → 5.22.2

== 0.4.0 -> 0.5.0

=== Változások

==== Általános
coff:ee frissítés 1.5.0 → 1.6.0

==== roaster-restassured
* Microprofile konfigból állítható injektálható ResponseProcessor (`@RestProcessor`, `ConfigurableResponseProcessor`)
* Az OpenAPITestHelper osztály `testOpenAPI` metódusa kiegészült `expectedOpenapiVersion` paraméterrel, hogy projekt szinten lehessen állítani.
Túlterheléssel megmaradt az eredeti szintaxis is, ezt hívva alapértelmezetten `3.0.3` az elvárt openapi verzió.
* Az OpenAPITestHelper osztályba bevezetésre került két felülírható metódus `decorateRequestSpecification`, `decorateValidatableResponse`.
Default működés esetén request és response logolást intézi, projekt szinten kikapcsolható/konfigurálható a logolás az osztály leszármaztatásával.
+
[source,java]
.Példa response log kikapcsolásra
----
@Model
@Alternative
@Priority(Interceptor.Priority.APPLICATION + 10)
public class ProjectOpenApiTestHelper extends OpenAPITestHelper {

    @Override
    protected ValidatableResponse decorateValidatableResponse(ValidatableResponse validatableResponse) {
//      return validatableResponse.log().all();
        return validatableResponse;
    }
}
----

==== Átállás
* `OpenAPITestHelper.testOpenAPI(java.lang.String)` a továbbiakban `3.0.1` helyett `3.0.3` OpenAPI verzióra futtat assertet.
Amennyiben ez projekt szinten nem felel meg a `OpenAPITestHelper.testOpenAPI(java.lang.String, java.lang.String)` metódussal felülírható az elvárt verzió.
+
[source,java]
.Példa response log kikapcsolásra
----
    @Test
    @DisplayName("Testing Sampple service /openapi")
    void testOpenapi() {
//    Default openapi test expected openapi version = 3.0.3
//    openAPITestHelper.testOpenAPI(projectSampleServiceBaseUri);
//    Openapi test with custom openapi version
      openAPITestHelper.testOpenAPI(projectSampleServiceBaseUri, "3.0.0");
    }
----