= Migrációs leírás

Következő szekció a verzió kiadások közötti változásokat írja le.

== 0.1.0 -> 0.2.0

=== Újdonságok

<<modules/modules-tm4j.adoc,TM4J - Test Management for Jira Modul>>

<<modules/modules-selenide.adoc,Selenide Modul>>

<<modules/modules-hibernate.adoc,Hibernate Modul>>

=== Változások
==== roaster-restassured
* A default JSON object mapper az idő értékeket ISO formátumra serializálja az eddigi "1600871093.907000000" helyett.

* Megszünt a deprecated lehetőség 

[source,java]
----
@Inject
private RestAssuredConfig restAssuredConfig;
----

Ezentúl már csak @JSON qualifier-el lehet használni

[source,java]
----
@Inject
@JSON
private RestAssuredConfig restAssuredConfig;
----

* Weld konténer enableDiscovery() módban fut, nem szükséges külön hozzáadni az osztályokat.
* hu.icellmobilsoft.roaster.restassured.BaseConfigurableWeldIT.configureWeld() depreceted lett.

==== Átállás

Az IT tesztekből ki kell venni az eddig manualisan hozzáadott bean-eket, egyébként 
"Bean name is ambiguous." hibaüzenetet kapunk.
[source,java]
----
@Deprecated
@Override
protected void configureWeld(Weld weld) {
    weld.addBeanClasses(SampleAction.class);
}
----

==== roaster-weldunit

* Weld konténer enableDiscovery() módban fut, nem szükséges külön hozzáadni az osztályokat.
* hu.icellmobilsoft.roaster.weldunit.BaseWeldUnitType.configureWeld() depreceted lett.

==== Átállás

A unit tesztekből ki kell venni az eddig manualisan hozzáadott bean-eket, egyébként 
"Bean name is ambiguous." hibaüzenetet kapunk.
[source,java]
----
@Deprecated
@Override
protected void configureWeld(Weld weld) {
    weld.addBeanClasses(SampleAction.class);
}
----

== 0.2.0 -> 0.3.0

=== Változások

==== Általános
coff:ee frissítés 1.2.1 → 1.3.0

==== roaster-hibernate
Az `EntityManagerProducer` osztályban az `EntityManagerFactory` injectálás törlésre került és a
`produceDefaultEntityManager()` metódus magában állítja elő, amikor szükség van rá.
Így mostantól már csak akkor jön létre alapértelmezett beállításokkal `EntityManagerFactory`,
ha `@HibernatePersistenceConfig` annotáció nélkül injectálunk `EntityManager`-t.

==== Átállás
A változtatások nem eredményeznek átállási munkálatokat, visszafelé kompatibilis.

==== roaster-tm4j
* Bugfix: Több teszt maven futtatása során már nem jön exception
* Bugfix: TM4J `Executed by` értékét újra töltik a tesztek
* TM4J environment értékét töltik a tesztek config paraméter alapján

==== Átállás
* A tesztosztályt (vagy ősét) fel kell annotálni a következővel: `@TestInstance(TestInstance.Lifecycle.PER_CLASS)`
* `roaster.tm4j.environment` config paraméterben megadott értéket létre kell hozni TM4J felületen amennyiben nem létezik
