= Configuration parameters

The tests can be parameterized using microprofile-config.
To achieve this, it is sufficient for the test class to extend either the `BaseConfigurableWeldIT` or `BaseWeldUnitType` abstract class.
Then, you can inject the desired configuration parameter using CDI in the usual way.
The configuration parameters can be set through the `META-INF/roaster-defaults.yml` configuration YAML file.
We can create additional YAML files for profiles alongside `roaster-defaults.yml`, named `roaster-{profile}.yml`.
The profiles to be executed can be set via the `profile` key on any default MP-Config source.
Multiple profiles can be specified separated by commas (`,`).
In this case, configuration keys are read starting from the first profile specified and continuing until the last one.

NOTE: If necessary, microprofile-Config allows adding new config sources.
So if the project requires it, it is possible to use configurations read from ETCD or a database.

Example:
[source,yaml]
.META-INF/roaster-defaults.yml
----
roaster:
    test:
        sample:
            url: http://roaster-default.hu
            port: 8083
            pass: secret
----

[source,yaml]
.META-INF/roaster-local.yml
----
roaster:
    test:
        sample:
            url: http://localhost
            port: 8084
----

[source,yaml]
.META-INF/roaster-sandbox.yml
----
roaster:
    test:
        sample:
            url: http://roaster-sandbox.hu
----

[source,java]
.GetSampleIT.java
----
@DisplayName("Testing Sample Rest")
@Tag(TestSuiteGroup.RESTASSURED)
public class GetSampleIT extends BaseConfigurableWeldIT {

    @Inject
    @ConfigProperty(name = "roaster.test.sample.url")
    private String sampleUrl;
    @Inject
    @ConfigProperty(name = "roaster.test.sample.port")
    private Integer samplePort;
    @Inject
    @ConfigProperty(name = "roaster.test.sample.pass")
    private Integer samplePass;
----


[source,bash]
.Profile running
----
~/project-backend/project-testsuite$ mvn verify -Dprofile=sandbox,local #<1>
----
<1> Profile running: Order of read YAMLs: roaster-sandbox.yml, roaster-local.yml, roaster-defaults.yml
+
Read values:
+
* `sampleUrl = http://roaster-sandbox.hu` (`roaster-sandbox.yml` from config)
* `samplePort = 8084` (In `roaster-sandbox.yml`, there are no values, so the configuration is read from `roaster-local.yml`)
* `samplePass = secret` (In `roaster-sandbox.yml` and `roaster-local.yml`, there are no values defined, so the configuration is read from `roaster-defaults.yml`)