[#modules-tm4j]
= TM4J

The purpose of this module is to automatically report the results of automated test cases to a configured TM4J (Test Management for Jira) server.

== Configuration

[source,yaml]
.META-INF/roaster-defaults.yml
----
roaster:
   tm4j:
      enabled: true #<1>
      projectKey: ABC #<2>
      testCycleKey: ABC-C1 #<3>
      environment: sandbox #<4>
      server/mp-rest/url: https://jira.example.com #<5>
      server/basicAuthToken: ZXhhbXBsZS11c2VyOnNlY3JldA== #<6>
      server/userName: #<7>
      server/password:
      cycle:
         foo: ABC-C2 #<8>
         bar: ABC-C3
----
<1> The TM4J server call can be disabled with this flag (default: false).
<2> Jira project key. It is usually the prefix of Jira issues.
<3> TM4J test cycle key. For example, ABC-C1 where ABC is the project key.
<4> (Optional) The name of the current environment where the tests are running. (Needs to be created in Jira)
<5> TM4J server URL.
<6> base64(userName + ":" + password)
<7> You can use either the server/userName + server/password or server/basicAuthToken parameters to provide server authentication information.
<8> Possibility to specify different TM4J test cycles per test tag.
If a test is tagged with a tag that is listed here (e.g., `@Tag("foo")` in JUnit 5), the result will be reported to the specified cycle instead of the default test cycle (testCycleKey configuration key).
If a test has multiple tags, the result will be reported to each corresponding cycle.

[TIP]
For security reasons, it is recommended not to include the basicAuthToken and password directly in the configuration file. Instead, you can pass them as command-line arguments to Maven.
For example: `$ mvn test -Droaster.tm4j.server/password=secret`

== Usage with JUnit 5

To use the module, you need to add the following Maven dependency to your pom.xml:

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-tm4j-junit5</artifactId>
</dependency>
----

After that, you just need to annotate the test classes/methods that you want to report the results of:

[source,java]
----
@ExtendWith(Tm4jExtension.class) // Activate the TM4J extension on the test class
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class ExampleTest extends BaseWeldUnitType {
    @Test
    @TestCaseId("ABC-T1") // Link the test case to TM4J
    void testOne() {
        assertTrue(1 + 1 == 2);
    }
}
----