= RestAssured

A RestAssured modul használatához csak be kell hivatkozni a pom.xml-ben

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-restassured</artifactId>
</dependency>
----

== RestAssured használata

A teszt fájlok a következő mintát követik:

[source,java]
----
@DisplayName("Testing XY service hu.icellmobilsoft.project.sample.service.rest.test.ISampleTestRest.postSampleRquest")
@Tag(TestSuiteGroup.RESTASSURED)
public class PostSampleRequestIT extends BaseConfigurableWeldIT {

    @Inject
    @ConfigProperty(name = "service.sample.uri")
    private String baseUri;

    @Inject
    @JSON
    private RequestSpecification requestSpecification;

    @Inject
    @JSON
    private ResponseSpecification responseSpecification;

    @Test
    @DisplayName("Testing opg generator json rest")
    void testSampleRest() {
        SampleRequest body = new SampleRequest();

        SampleResponse actual = RestAssured
                // given
                .given()//
                .spec(requestSpecification)//
                .config(restAssuredConfig).body(body) //
                .baseUri(baseUri) //
                // when
                .when()//
                .log().all()//
                .post("/sample")
                // then
                .then()//
                .log().all()//
                .spec(responseSpecification)//
                .extract().response().getBody().as(SampleResponse.class);
        Assertions.assertEquals(FunctionCodeType.OK, actual.getFuncCode());
    }
}
----

=== RestAssured default beállításai

Alapértelmezetten XML vagy JSON formátumra van támogatás a rendszerben.
A beállításokat a következő osztályok kezelik:

* RestAssuredConfigProducer
* RequestSpecificationProducer
* ResponseSpecificationProducer

Mind szabadon módosíthatóak az implementáló projekten.

==== JSON default beállításai

* A request content-type és accept "application/json".
* A response HTTP status 200 és "application/json" accept.
* A default beállításokat a Jackson2ObjectMapperFactoryImpl foglalja össze.

Ha igény van egy saját ObjectMapperConfig-ra,
mint ami a ObjectMapperConfigProducer-ben keletkezik,
akkor minta megoldásnak használható például:

[source,java]
----
@Inject
@JSON
private RestAssuredConfig restAssuredConfig;
 
((Jackson2ObjectMapperFactoryImpl) restAssuredConfig.getObjectMapperConfig().jackson2ObjectMapperFactory()).getObjectMapper()
        .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
----

==== XML default beállításai

* Kódolás UTF-8.
* A request content-type és accept "application/xml".
* A response HTTP status 200 és "application/xml" accept.


=== ResponseProcessor

==== Implementálása

Egy adott endpoint tesztelésének segítésére született meg a `ResponseProcessor` absztrakt osztály.
Leszármazástatáskor meg kell adni a Response típusát generikus paraméterben,
valamint implementálni kell 2 String-et visszaadó metódust, hogy az endpoint-ot azonosítsuk:

* `baseUriKey`: A Roaster konfigurációban használt kulcs, ami megadja az endpoint baseUri-jét
* `path`: Az endpoint path. Pl.: http://localhost/foo/bar esetén: /foo/bar

Opcionálisan az osztály többi metódusa is felülírható,
hogy a request-et vagy a response foldolgozását személyre szabhassuk.
Például a `createRequestSpecification` metódust felülírva
módosíthatjuk a request header-öket, sütiket, stb.

==== Használata

A `ResponseProcessor` implementáció `getJson`, `postJson`, `getXml`, `postXml` metódusait
használva tudjuk meghívni az endpoint-ot és automatán parse-olni a választ.

==== Példa

[source,java]
----
public class ExampleQueryResponseProcessor extends ResponseProcessor<ExampleQueryResponse> {

    @Override
    public String baseUriKey() {
        return "example-project.example-service.url"; // értéke pl.: http://localhost:8080
    }

    @Override
    public String path() {
        return "/example/foo/{id}";
    }

    @Override // Példa extra header hozzáadására
    protected RequestSpecification createRequestSpecification(RequestSpecification initRequestSpecification) {
        return super.createRequestSpecification(initRequestSpecification)
                .header("Authorization", "Basic dXNlcjpwYXNz");
    }

    public ExampleQueryResponse queryWithJson(String id) {
        return getJson(ExampleQueryResponse.class, id);
    }

    public ExampleQueryResponse queryWithXml(String id) {
        return getXml(ExampleQueryResponse.class, id);
    }
}
----
