[#modules-redis]
= REDIS

To use the Redis module, you just need to reference it in the pom.xml file.

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-redis</artifactId>
</dependency>
----

== REDIS Configuration Parameters

The necessary data for accessing Redis can be parameterized using microprofile-config.

Example:

[source,properties]
.META-INF/microprofile-config.properties
----
roaster.redis.default.host=example.com
roaster.redis.default.port=6379
roaster.redis.default.password=redispass
roaster.redis.default.database=0
roaster.redis.default.pool.maxtotal=8
roaster.redis.default.pool.maxidle=4
----

[source,yml]
.META-INF/roaster-defaults.yml
----
roaster:
    redis:
        default:
            host: example.com
            port: 6379
            password: redispass
            database: 0
            pool:
                maxtotal: 8
                maxidle: 4
----

== Using REDIS

First, you need to inject the handler class.

[source,java]
.Injecting the handler
----
    @Inject
    private RedisHandler redisHandler;
----

Or you can instantiate with the new operator:

[source,java]
----
    private final RedisHandler redisHandler = new RedisHandler();
----

=== Operations of RedisHandler
Through RedisHandler, operations are accessed, creating a RedisService using CDI each time they are invoked. RedisService is instantiated with the data defined by redisConfigKey, and operations are forwarded to it.

The redisConfigKey is the third tag in the keys specified in microprofile-config.properties, e.g:
coffee.redis.default.host -> default

Operations taken from RedisService:

* getRedisData(redisConfigKey, valueKey, class)
* getRedisDataOpt(redisConfigKey, valueKey, class)
* setRedisData(redisConfigKey, valueKey, redisData)
* setRedisDataExp(redisConfigKey, valueKey, secondsToExpire, redisData)
* removeRedisData(redisConfigKey, valueKey)
* removeAllRedisData(redisConfigKey, List<valueKey>)
* removeAllRedisData(redisConfigKey)

[source,java]
.Example of operation calls
----
String data = redisHandler.getRedisData("default", "1234", String.class);
String newData = redisHandler.setRedisData("default", "1234", "new data");
redisHandler.removeAllRedisData("default");
----

== Jedis

To use jedis directly, you can get a connection from the `JedisConnectionCache`:

[source,java]
----
    private final UnifiedJedis jedis = JedisConnectionCache.get("default");

    void test() {
        jedis.set(key, value);
        jedis.get(key);
    }
----

== Redis stream publish

To publish to a redis stream, you can use the `hu.icellmobilsoft.roaster.redis.RedisStreamPublisher` class:

[source,java]
----
    private final RedisStreamPublisher publisher = new RedisStreamPublisher(
            "default",
            "examplePreparator");

    void test() {
        publisher.publish(id);
        publisher.publish(JsonUtil.toJsonEx(dto), Map.of(...));
    }
----
