= Jaxrs

To use the JAX-RS module, you just need to reference it in the pom.xml file.

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-jaxrs</artifactId>
</dependency>
----

== Using Jaxrs

The test files adhere to the Jakarta EE JAX-RS specification, specifically using the RestEasy implementation.

=== RestAssured default settings

By default, the system supports XML or JSON formats.

.JSON response settings

* The response HTTP status is 200 and "application/json" is accepted.

.XML response settings

* The response HTTP status is 200 and "application/xml" is accepted.

=== ResponseProcessor

==== Implementation

The abstract class `hu.icellmobilsoft.roaster.jaxrs.response.ResponseProcessor` was created to assist in testing a specific endpoint.
When inheriting, you need to specify the Response type as a generic parameter and implement two methods that return strings to identify the endpoint.

* `baseUriKey`: The key used in Roaster configuration to specify the base URI of the endpoint
* `path`: The endpoint path. For example, in http://localhost/foo/bar, it would be: /foo/bar

Optionally, the other methods of the class can also be overridden to customize request or response processing.

==== Usage

Using methods like `getOctetStream`, `postMultipartJson`, `postMultipartXml`, etc., implemented in the `ResponseProcessor`, we can invoke the endpoint and automatically parse the response.

=== ConfigurableResponseProcessor

To avoid implementing a separate `ResponseProcessor` for each REST endpoint, the `ConfigurableResponseProcessor` class was created. This class reads necessary values from configuration, such as `baseUriKey` and `path`.

==== Usage

In the configuration, the `baseUriKey` and `path` should be added under a common prefix. Optionally, `headers` can also be specified here.
In YAML format, it looks like this:

[source,yml]
----
testsuite:
    rest:
        exampleService:
            example:
                baseUriKey: example-project.example-service.url
                path: /rest/exampleService/example/{id}
            headerExample:
                baseUriKey: example-project.example-service.url
                path: /rest/exampleService/example/{id}
                headers:
                    - "X-LANGUAGE: hu"
                    - "User-Agent: roaster/0.8 restassured"
----

You can inject the `ConfigurableResponseProcessor` into the test class using the `@RestProcessor` qualifier, specifying the configuration prefix.

[source,java]
----
import hu.icellmobilsoft.roaster.jaxrs.response.producer.impl.ConfigurableResponseProcessor;

class ExampleTest {
    @Inject
    @RestProcessor(configKey = "testsuite.rest.exampleService.example") //<1>
    private ConfigurableResponseProcessor<ExampleResponse> responseProcessor;

    @Inject
    @RestProcessor(
            configKey = "testsuite.rest.exampleService.example",
            expectedStatusCode = HttpStatus.SC_BAD_REQUEST //<2>
    )
    private ConfigurableResponseProcessor<ExampleResponse> badRequestResponseProcessor;

    void test() {
        MultipartFormDataOutput multipartbody = new MultipartFormDataOutput();
        multipartbody.addFormData("part1", "part1Body", javax.ws.rs.core.MediaType.APPLICATION_JSON_TYPE);
        multipartbody.addFormData("part2", "part2Body", javax.ws.rs.core.MediaType.APPLICATION_JSON_TYPE);
        String response = processor.postMultipartJson(multipartbody, String.class, "jsonEntityId");
        Assertions.assertEquals(JsonUtil.toJson(RESPONSE_DTO), response);
    }
}
----
<1> Basic example of injecting `ConfigurableResponseProcessor`:
<2> Optionally, the expected response status code can also be specified in the annotation (default: `200 OK`).
<3> In `ConfigurableResponseProcessor`, you can also specify the query parameters.

==== Own implementation

If you want to extend the functionality of ConfigurableResponseProcessor within the project,
(for example: for handling login or other project-specific header operations),
you can do so by first implementing `AbstractConfigurableResponseProcessor`:

[source,java]
----
import hu.icellmobilsoft.roaster.jaxrs.response.producer.spi.AbstractConfigurableResponseProcessor;

@Dependent
public class CustomConfigurableResponseProcessor<RESPONSE> extends AbstractConfigurableResponseProcessor<RESPONSE> {

    // We override what is necessary...
}
----

After this, you need to create a CDI producer that provides the configured instances:

[source,java]
----
import hu.icellmobilsoft.roaster.jaxrs.response.producer.spi.AbstractConfigurableResponseProcessorProducer;

@Dependent
public class CustomConfigurableResponseProcessorProducer<RESPONSE> extends AbstractConfigurableResponseProcessorProducer<LoginConfigurableResponseProcessor<RESPONSE>> {
    @Override
    @Produces //<1>
    @RestProcessor(configKey = "")
    public CustomConfigurableResponseProcessor<RESPONSE> createCustomResponseProcessor(InjectionPoint injectionPoint) {
        return super.createConfiguredResponseProcessor(injectionPoint);
    }

    @Override
    protected CustomConfigurableResponseProcessor<RESPONSE> getBaseResponseProcessor() { //<2>
        return CDI.current().select(CustomConfigurableResponseProcessor.class).get();
    }
}
----
<1> You need to create a producer method (`createCustomResponseProcessor` where you can obtain a pre-configured instance when invoked)
<2> You need to override the `getBaseResponseProcessor` method to return our type (which will be configured by `createCustomResponseProcessor`)

After this, you can use your own implementation, either alongside the default solution, in a test.

[source,java]
----
import hu.icellmobilsoft.roaster.jaxrs.response.producer.impl.ConfigurableResponseProcessor;

class ExampleTest {
    @Inject
    @RestProcessor(configKey = "testsuite.rest.exampleService.example")
    private CustomConfigurableResponseProcessor<ExampleResponse> customResponseProcessor;
...
}
----

== Microprofile Rest Client
The MicroProfile Rest Client itself uses the JAX-RS fundamentals, so JAX-RS implementations inherently support it.
For example, in the case of RestEasy, a more detailed description can be found here:
https://docs.jboss.org/resteasy/docs/4.7.5.Final/userguide/html/MicroProfile_Rest_Client.html[MicroProfile Rest Client]

The Roaster dependency provides support for using the MicroProfile Rest Client.

.Simple MicroProfile Rest Client API example
[source,java]
----
import javax.ws.rs.Consumes;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import hu.icellmobilsoft.coffee.dto.common.commonservice.BaseRequest;
import hu.icellmobilsoft.coffee.dto.exception.BaseException;

@RegisterRestClient
public interface TestMpRestApi {

    @POST
    @Path("/mp/rest/client/post")
    @Produces(value = { MediaType.APPLICATION_JSON })
    @Consumes(value = { MediaType.APPLICATION_JSON })
    String testPost(BaseRequest baseRequest) throws BaseException;
}
----

.Using MicroProfile Rest Client API
[source,java]
----
TestMpRestApi testMpRestApiImpl = RestClientBuilder.newBuilder()
    // set URI
    .baseUri(URI.create(System.getProperty(URI_KEY)))
    // build API interface
    .build(TestMpRestApi.class);
String response = testMpRestApiImpl.testPost(DtoHelper.createBaseRequest());
----

