= TestDoc

The purpose of the TestDoc module is to generate AsciiDoc documentation from test classes.

== Usage

To activate the TestDoc module, you need to reference the following dependency in your pom.xml:

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-testdoc</artifactId>
</dependency>
----

Afterwards, annotate the test classes you want to document with the @TestDoc annotation.

Once you've done this, by default, during compilation, the generated AsciiDoc will be included in the resulting `.jar` file under the name `META-INF/test_doc.adoc`.
Each test class appears in a separate table in the generated document.

== Example

*Input:*

[source,java]
----
@TestDoc(titleHeadingLevel = 3) // <1>
@DisplayName("Example test class")
class TestDocExampleTest {

    @Test // <2>
    @DisplayName("Example test method in TestDocExampleTest class")
    @Disabled("only for example")
    void exampleTestMethod() {
        Assertions.assertTrue(true);
    }

    @ParameterizedTest // <2>
    @NullSource
    @DisplayName("Example parameterized test method in TestDocExampleTest class")
    @Disabled("only for example")
    void exampleParameterizedTestMethod(String param) {
        Assertions.assertNull(param);
    }
}




@TestDoc(titleHeadingLevel = 3)  // <1>
@DisplayName("Testing TestDoc functions")
class TestDocTest {

    @Test // <2>
    @DisplayName("Generated file should contain the test data")
    void generatedFileShouldContainTestData() throws URISyntaxException, IOException {
        URL generatedFileUrl = getClass().getResource("/" + TestDocConfig.DEFAULT_OUTPUT_PATH + TestDocConfig.DEFAULT_OUTPUT_FILE_NAME);
        assertNotNull(generatedFileUrl);

        String generatedFile = Files.readString(Paths.get(generatedFileUrl.toURI()));

        // classes
        assertTrue(generatedFile.contains("Testing TestDoc functions"));
        assertTrue(generatedFile.contains("Example test class"));

        // methods
        assertTrue(generatedFile.contains("generatedFileShouldContainTestData"));
        assertTrue(generatedFile.contains("exampleTestMethod"));

        // display names
        assertTrue(generatedFile.contains("Generated file should contain the test data"));
        assertTrue(generatedFile.contains("Example test method in TestDocExampleTest class"));
    }
}
----

<1> The generation is activated on a class using the `@TestDoc` annotation.
The `titleHeadingLevel` parameter is used to set the heading level of the generated table's title row, and its specification is optional.
If specified, the value must fall within the interval [0, 5].
If not specified or if the provided value falls outside the interval, the default value will be 2.
<2> Methods annotated with `@Test` and `@ParameterizedTest` will be included in the generated table.

Each class will have a separate table generated in the resulting document.
The order of tables will follow the names of the test classes.
The heading of the tables will primarily be based on the `@DisplayName` value of the class. If this is not filled out, then it will default to the class name.
The tables will contain the test method name and its corresponding `@DisplayName` value, if provided.

*Output:*

=== Example test class
[cols="1,3",options=header,stripes=even]
|===
|Method name|Display name
|exampleTestMethod|Example test method in TestDocExampleTest class
|exampleParameterizedTestMethod|Example parameterized test method in TestDocExampleTest class
|===
=== Testing TestDoc functions
[cols="1,3",options=header,stripes=even]
|===
|Method name|Display name
|generatedFileShouldContainTestData|Generated file should contain the test data
|===

== Configuration

Since the generation uses an annotation processor, you can configure it during compilation using the `-A` switch.
For Maven, this can be done via `maven-compiler-plugin`:

.pom.xml example
[source,xml]
----
<build>
    <plugins>
        <plugin>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
                <compilerArgs>
                    <arg>-Aroaster.testDoc.outputDir=${project.basedir}/../docs/</arg> #<1>
                    <arg>-Aroaster.testDoc.outputFileName=${project.name}_test_doc.adoc</arg> #<2>
                    <arg>-Aroaster.testDoc.outputToClassPath=false</arg> #<3>
                </compilerArgs>
            </configuration>
        </plugin>
    </plugins>
</build>
----

<1> The folder where the generated file will be placed.
Default: `META-INF/`
<2> The name of the generated file.
Default: `test_doc.adoc`
<3> Should the generated file be placed on the classpath, meaning do we want it to be included in the resulting JAR file?
Default: `true`
