[#modules-hibernate]
= Hibernate

To use the Hibernate module, you first need to reference the following dependency in your pom.xml file:

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-hibernate-cdi</artifactId>
</dependency>
----

In addition, you also need to add the appropriate JDBC driver, which may vary depending on the usage context.
It is recommended to use the following:

[source,xml]
.pom.xml in case of Oracle19
----

        <dependency>
            <groupId>com.oracle.ojdbc</groupId>
            <artifactId>ojdbc10</artifactId>
            <version>19.3.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.oracle.ojdbc</groupId>
            <artifactId>orai18n</artifactId>
            <version>19.3.0.0</version>
        </dependency>

----

[source,xml]
.pom.xml in case of Mysql
----
        <!-- https://mvnrepository.com/artifact/mysql/mysql-connector-java -->
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.22</version>
        </dependency>

----

[source,xml]
.pom.xml in case of H2
----
        <!-- https://mvnrepository.com/artifact/com.h2database/h2 -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>1.4.200</version>
        </dependency>

----

[source,xml]
.pom.xml in case of PostgreSQL
----
        <!-- https://mvnrepository.com/artifact/org.postgresql/postgresql -->
        <dependency>
        <groupId>org.postgresql</groupId>
        <artifactId>postgresql</artifactId>
        <version>42.2.18</version>
        </dependency>

----

In addition, the following configurations need to be performed:

== Hibernate configuration parameters

To use Hibernate, it is necessary to create the `persistence.xml` file at the project level within the `META-INF` folder among resources.
If it is created with the name *defaultPU* (as in the example), then the EntityManager can be injected without any extra annotations.

Example:

[source,xml]
.META-INF/persistence.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence
             http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd"
             version="2.1">

    <persistence-unit name="defaultPU">
        <mapping-file>META-INF/jpa-entity.xml</mapping-file>
    </persistence-unit>
</persistence>

----

[TIP]
In the `persistence.xml`, it is necessary to specify the entities regardless!
For further custom settings, you can find a simple description here: https://vladmihalcea.com/jpa-persistence-xml/
Settings provided through microprofile-config will be used, overriding identical properties in the persistence.xml.
If a specific part is not configured in microprofile-config but is configured in persistence.xml, then the settings in persistence.xml will be applied.

Hibernate configuration settings can be parameterized using microprofile-config.

Example:

[source,properties]
.META-INF/microprofile-config.properties
----
roaster.hibernate.defaultPU.jdbc.driver=oracle.jdbc.OracleDriver
roaster.hibernate.defaultPU.jdbc.url=jdbc:oracle:thin:@//localhost:1521/XE
roaster.hibernate.defaultPU.jdbc.user=db_username
roaster.hibernate.defaultPU.jdbc.password=*****
roaster.hiberante.defaultPU.jdbc.log_warnings=true
roaster.hibernate.defaultPU.hibernate.default_schema=user_schema
roaster.hibernate.defaultPU.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
roaster.hibernate.defaultPU.hibernate.show_sql=true
roaster.hibernate.defaultPU.hibernate.format_sql=true
roaster.hiberante.defaultPU.hibernate.log_session_metrics=true
roaster.hiberante.defaultPU.hibernate.generate_statistics=true
----

[source,yml]
.META-INF/roaster-defaults.yml
----
  roaster:
    hibernate:
      defaultPU:
        jdbc:
          driver: oracle.jdbc.OracleDriver
          url: jdbc:oracle:thin:@//localhost:1521/XE
          user: db_username
          password: *****
          log_warnings: true
        hibernate:
          default_schema: user_schema
          dialect: org.hibernate.dialect.Oracle12cDialect
          show_sql: true
          format_sql: true
          log_session_metrics: true
          generate_statistics: true
----

== Example of usage

[source,java]
.HibernateTest example class
----
public class HibernateTest extends BaseWeldUnitType {

    @Inject
    // This applies in the background: @HibernatePersistenceConfig(persistenceUnitName = "defaultPU")
    private EntityManager userEntityManager;

    @Inject
    @HibernatePersistenceConfig(persistenceUnitName = "otherPu")
    private EntityManager otherEntityManager;

    @Test
    public void testEntityManager() {
        Assertions.assertNotNull(userEntityManager);
        SecurityUser securityUser = userEntityManager.find(SecurityUser.class, "0");
        Assertions.assertNotNull(securityUser);
        Assertions.assertNotNull(otherEntityManager);
        OtherEntity other = userEntityManager.find(OtherEntity.class, "0");
        Assertions.assertNotNull(other);
    }


    @Test
    public void testUseEntityManager() {
        Assertions.assertNotNull(userEntityManager);

        User user = userEntityManager.find(User.class,"FD34123");
        Assertions.assertNotNull(user);

        CriteriaBuilder builder = userEntityManager.getCriteriaBuilder();
        CriteriaQuery<User> criteriaQuery = builder.createQuery(User.class);
        Root<User> root = criteriaQuery.from(User.class);
        criteriaQuery.select(root);
        List<Order> os = new ArrayList<>();
        os.add(builder.asc(root.get(User_.creationDate)));
        criteriaQuery.orderBy(os);
        TypedQuery<User> query = userEntityManager.createQuery(criteriaQuery);
        List<User> resultList = query.getResultList();
        // Assertions resultList

        CriteriaQuery<Long> countCriteriaQuery = builder.createQuery(Long.class);
        Root<User> countRoot = countCriteriaQuery.from(User.class);
        countCriteriaQuery.select(builder.count(countRoot));
        TypedQuery<Long> countQuery = userEntityManager.createQuery(countCriteriaQuery);
        Long count = countQuery.getSingleResult();
        // Assertions count
    }

}
----

== Hibernate SE module

There is a newer module, where we can use the configured Hibernate without a CDI/Weld container.
This method can be faster and can be applied in multithreaded environments, i.e. in parallel tests.

To use this module we should add this dependency to the pom.xml instead of `roaster-hibernate-cdi`:

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-hibernate-se</artifactId>
</dependency>
----

After that the previous example can be rewritten like this:

[source,java]
----
public class HibernateTest {

    private EntityManager userEntityManager = EntityManagerCache.getForDefaultPersistenceUnit();
    private EntityManager otherEntityManager = EntityManagerCache.getForPersistenceUnit("otherPu");

    // ...
}
----

The `EntityManagerCache` closes all created `EntityManagerFactory`-s so the DB connection pools at the shutdown of the JVM, even if the test run was canceled.
The entity audit data can be customized by calling the `EntityManagerFactoryCache#setPrincipalSupplier` method.
