[#modules-selenide]
= Selenide

To use the Selenide module, you just need to reference it in the pom.xml file.

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-selenide-api</artifactId>
</dependency>
----

*The Selenide module is not compatible with Internet Explorer!!*

== Selenide Configuration Parameters

The Selenide and WebDriver parameters can be configured using microprofile-config.

Examples:

[source,properties]
.META-INF/microprofile-config.properties
----
roaster.selenide.homepage=https://google.com
roaster.selenide.timeout=3000
roaster.selenide.selenium.url=https://localhost:9999/wd/hub
roaster.selenide.browser.type=chrome
roaster.selenide.browser.headless=true
roaster.selenide.browser.device=Galaxy S5
roaster.selenide.browser.decision.width=1024
roaster.selenide.browser.decision.height=768
----

[source,yml]
.META-INF/roaster-defaults.yml
----
# Minimal Roaster config for Selenide
roaster:
  selenide:
    homepage: https://google.com # URL of the page that opens in the browser
    timeout: 3000 # default timeout for WebDriver
    selenium:
      url: # URL of wd hub if tests need to be run with remote WebDriver
    browser:
      type: chrome # possible values: chrome, edge, opera, safari
      headless: false
      device: # Galaxy S5 or iPad Pro (See options here: https://github.com/DevExpress/device-specs/blob/master/devices.md)
      decision:
        width: # example: 1024
        height: # example: 768
----

It's important to note that if *roaster.selenide.selenium.url* is not filled, it won't run in remote mode.

It's important to note that if *roaster.selenide.browser.device* is filled, the Chrome browser will be launched, emulating the device with the specified name.
It's important to remember that since the emulated device has a fixed screen size, that will be used, and it won't take into account the resolution settings.

It's important to note that if *roaster.selenide.browser.device.width* and *roaster.selenide.browser.device.height* are filled, the browser won't be adjusted to the screen.

== Usage Example

[source,java]
.GoogleIcellMobilsoftTest sample class
----
@Tag(TestSuiteGroup.SELENIDE)
@Disabled("Only for testing!!!")
public class GoogleIcellMobilsoftTest extends BaseSelenideTestCase {

    @Test
    @DisplayName("Search 'icellmobilsoft' word on Google.com")
    @Disabled("Only for testing!!!")
    public void testGoogleWithIcellmobilsoftSearch() {
        // You don't have to use Selenide.open(<url>), it comes from the configuration and does it automatically
        SelenideElement qInput = Selenide.$("input[name='q']");
        qInput.setValue("icellmobilsoft").pressEnter();

        SelenideElement result = Selenide.$("div[id='search']");
        ElementsCollection resultList = result.$$("div[class='g'] a[href='https://icellmobilsoft.hu/hu/'");
        resultList.first().shouldHave(Condition.visible);
    }
}
----

== Selenide Angular Module

The purpose of this module is to support more complex components used in Angular.

To use it, you need

 to include the following Maven module:

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-selenide-angular</artifactId>
</dependency>
----

Currently supported components:

=== <mat-checkbox>

[source,java]
.example
----
MatCheckbox checkbox = new MatCheckbox(Selenide.$(MatCheckbox.TAG_NAME));
assertFalse(checkbox.getValue());
checkbox.toggle();
assertTrue(checkbox.getValue());
----

=== <mat-radio-group>

[source,java]
.example
----
MatRadioGroup radioGroup = new MatRadioGroup(Selenide.$(MatRadioGroup.TAG_NAME));
assertTrue(radioGroup.getSelected().isEmpty());
radioGroup.select("Option 2");
assertEquals("Option 2", radioGroup.getSelected().orElseThrow());
assertIterableEquals(List.of("Option 1", "Option 2"), radioGroup.getOptions());
----

=== <mat-select>

[source,java]
.example
----
MatSelect multiSelect = new MatSelect(Selenide.$("#select-multiple " + MatSelect.TAG_NAME));
multiSelect.select("Onion", "Pepperoni");
assertIterableEquals(List.of("Onion", "Pepperoni"), multiSelect.getSelected());
multiSelect.select("Tomato");
assertIterableEquals(List.of("Tomato"), multiSelect.getSelected());
assertEquals(6, multiSelect.getOptions().size());
----

=== <mat-slide-toggle>

[source,java]
.example
----
MatSlideToggle checkbox = new MatSlideToggle(Selenide.$(MatSlideToggle.TAG_NAME));
assertFalse(checkbox.getValue());
checkbox.toggle();
assertTrue(checkbox.getValue());
----