= REDIS

To use the Redis module, you just need to reference it in the pom.xml file.

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-redis</artifactId>
</dependency>
----

== REDIS Configuration Parameters

The necessary data for accessing Redis can be parameterized using microprofile-config.

Example:

[source,properties]
.META-INF/microprofile-config.properties
----
coffee.redis.default.host=example.com
coffee.redis.default.port=6379
coffee.redis.default.password=redispass
coffee.redis.default.database=0
coffee.redis.default.pool.maxtotal=128
coffee.redis.default.pool.maxidle=32
----

[source,yml]
.META-INF/roaster-defaults.yml
----
coffee:
    redis:
        default:
            host: example.com
            port: 6379
            password: redispass
            database: 0
            pool:
                maxtotal: 128
                maxidle: 32
----

== Using REDIS

First, you need to inject the handler class.

[source,java]
.Injecting the handler
----
    @Inject
    private RedisHandler redisHandler;
----

=== Operations of RedisHandler
Through RedisHandler, operations are accessed, creating a RedisService using CDI each time they are invoked. RedisService is instantiated with the data defined by redisConfigKey, and operations are forwarded to it.

The redisConfigKey is the third tag in the keys specified in microprofile-config.properties, e.g:
coffee.redis.default.host -> default

Operations taken from RedisService:

* getRedisData(redisConfigKey, valueKey, class)
* getRedisDataOpt(redisConfigKey, valueKey, class)
* setRedisData(redisConfigKey, valueKey, redisData)
* setRedisDataExp(redisConfigKey, valueKey, secondsToExpire, redisData)
* removeRedisData(redisConfigKey, valueKey)
* removeAllRedisData(redisConfigKey, List<valueKey>)
* removeAllRedisData(redisConfigKey)

[source,java]
.Example of operation calls
----
String data = redisHandler.getRedisData("default", "1234", String.class);
String newData = redisHandler.setRedisData("default", "1234", "new data");
redisHandler.removeAllRedisData("default");
----
