= RestAssured

To use the RestAssured module, you just need to reference it in the pom.xml file.

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-restassured</artifactId>
</dependency>
----

== Using RestAssured

The test files follow the following pattern:

[source,java]
----
@DisplayName("Testing XY service hu.icellmobilsoft.project.sample.service.rest.test.ISampleTestRest.postSampleRquest")
@Tag(TestSuiteGroup.RESTASSURED)
public class PostSampleRequestIT extends BaseConfigurableWeldIT {

    @Inject
    @ConfigProperty(name = "service.sample.uri")
    private String baseUri;

    @Inject
    @JSON
    private RequestSpecification requestSpecification;

    @Inject
    @JSON
    private ResponseSpecification responseSpecification;

    @ParameterizedTest
    @CsvSource({ "1, 1, 2", "2, 3, 5", })
    @ExplicitParamInjection
    void test(int a, int b, int expectedSum) {
      Assertions.assertEquals(expectedSum, a + b);
    }

    @Test
    @DisplayName("Testing opg generator json rest")
    void testSampleRest() {
        SampleRequest body = new SampleRequest();

        SampleResponse actual = RestAssured
                // given
                .given()//
                .spec(requestSpecification)//
                .config(restAssuredConfig).body(body) //
                .baseUri(baseUri) //
                // when
                .when()//
                .log().all()//
                .post("/sample")
                // then
                .then()//
                .log().all()//
                .spec(responseSpecification)//
                .extract().response().getBody().as(SampleResponse.class);
        Assertions.assertEquals(FunctionCodeType.OK, actual.getFuncCode());
    }
}
----

=== Default settings of RestAssured

By default, the system supports XML or JSON formats.
The settings are managed by the following classes:

* RestAssuredConfigProducer
* RequestSpecificationProducer
* ResponseSpecificationProducer

All of them can be freely modified in the implementing project.

==== Default settings of JSON

* The request content-type and accept headers are "application/json".
* The response HTTP status is 200 and "application/json" is accepted.
* The default settings are summarized by Jackson2ObjectMapperFactoryImpl.

If there is a need for a custom ObjectMapperConfig,
similar to what is generated in ObjectMapperConfigProducer,
a sample solution could be:

[source,java]
----
@Inject
@JSON
private RestAssuredConfig restAssuredConfig;
 
((Jackson2ObjectMapperFactoryImpl) restAssuredConfig.getObjectMapperConfig().jackson2ObjectMapperFactory()).getObjectMapper()
        .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
----

==== Default settings of XML

* Encoding UTF-8.
* The request content-type and accept headers are "application/xml".
* The response HTTP status is 200 and "application/xml" is accepted.


=== ResponseProcessor

==== Implementation

The `ResponseProcessor` abstract class was created to assist in testing a specific endpoint.
When subclassing, you need to specify the response type in a generic parameter and implement two methods that return strings to identify the endpoint:

* `baseUriKey`: The key used in the Roaster configuration that specifies the baseURI of the endpoint
* `path`: The endpoint path. For example, in http://localhost/foo/bar, it would be: /foo/bar

Optionally, other methods of the class can also be overridden to customize the processing of requests or responses.
For example, by overriding the `createRequestSpecification` method, you can modify the request headers, cookies, etc.

==== Usage

Using the `getJson`, `postJson`, `getXml`, `postXml` methods of the `ResponseProcessor` implementation, we can invoke the endpoint and automatically parse the response.

==== Example

[source,java]
----
public class ExampleQueryResponseProcessor extends ResponseProcessor<ExampleQueryResponse> {

    @Override
    public String baseUriKey() {
        return "example-project.example-service.url"; // value e.g: http://localhost:8080
    }

    @Override
    public String path() {
        return "/example/foo/{id}";
    }

    @Override // Example of adding an extra header
    protected RequestSpecification createRequestSpecification(RequestSpecification initRequestSpecification) {
        return super.createRequestSpecification(initRequestSpecification)
                .header("Authorization", "Basic dXNlcjpwYXNz");
    }

    public ExampleQueryResponse queryWithJson(String id) {
        return getJson(ExampleQueryResponse.class, id);
    }

    public ExampleQueryResponse queryWithXml(String id) {
        return getXml(ExampleQueryResponse.class, id);
    }
}
----

=== ConfigurableResponseProcessor

To avoid implementing a separate `ResponseProcessor` for each REST endpoint,
the `ConfigurableResponseProcessor` class has been created. It reads necessary values from configuration,
such as `baseUriKey` and `path`.

==== Usage

To configure, you need to include `baseUriKey` and `path` under a common prefix.
Optionally, `headers` can also be provided. In YAML format, it looks like this:

[source,yml]
----
testsuite:
    rest:
        exampleService:
            example:
                baseUriKey: example-project.example-service.url
                path: /rest/exampleService/example/{id}
            headerExample:
                baseUriKey: example-project.example-service.url
                path: /rest/exampleService/example/{id}
                headers:
                    - "X-LANGUAGE: hu"
                    - "User-Agent: roaster/0.5 restassured"
----

In the test class, you can inject the `ConfigurableResponseProcessor` using the `@RestProcessor` qualifier,
providing the configuration prefix:
[source,java]
----
import hu.icellmobilsoft.roaster.restassured.response.producer.impl.ConfigurableResponseProcessor;

class ExampleTest {
    @Inject
    @RestProcessor(configKey = "testsuite.rest.exampleService.example") //<1>
    private ConfigurableResponseProcessor<ExampleResponse> responseProcessor;

    @Inject
    @RestProcessor(
            configKey = "testsuite.rest.exampleService.example",
            expectedStatusCode = HttpStatus.SC_BAD_REQUEST //<2>
    )
    private ConfigurableResponseProcessor<ExampleResponse> badRequestResponseProcessor;

    void test() {
        responseProcessor.setQueryParams(Map.of("foo", "42")); //<3>
        ExampleResponse response = responseProcessor.getJson(ExampleResponse.class, "XXX");
        // asserts...
    }
}
----
<1> Basic example of injecting `ConfigurableResponseProcessor`
<2> Optionally, the expected response status code can also be specified in the annotation (default: `200 OK`)
<3> In `ConfigurableResponseProcessor`, you can also specify query parameters

==== Own implementation

If you want to extend the functionality of `ConfigurableResponseProcessor` within your project (e.g., for handling login or other project-specific headers),
you can first implement `AbstractConfigurableResponseProcessor`:

[source,java]
----
import hu.icellmobilsoft.roaster.restassured.response.producer.spi.AbstractConfigurableResponseProcessor;

@Dependent
public class LoginConfigurableResponseProcessor<RESPONSE> extends AbstractConfigurableResponseProcessor<RESPONSE> {
    @Inject
    private LoginHandler loginHandler;

    @Override
    protected RequestSpecification createRequestSpecification(RequestSpecification initRequestSpecification) {
        loginHandler.login();
        return super.createRequestSpecification(initRequestSpecification)
                .headers(loginHandler.loginHeaders());
    }
}
----

After this, you need to create a CDI producer that serves the configured instances:

[source,java]
----
import hu.icellmobilsoft.roaster.restassured.response.producer.spi.AbstractConfigurableResponseProcessorProducer;

@Dependent
public class LoginConfigurableResponseProcessorProducer<RESPONSE> extends AbstractConfigurableResponseProcessorProducer<LoginConfigurableResponseProcessor<RESPONSE>> {
    @Override
    @Produces //<1>
    @RestProcessor(configKey = "")
    public LoginConfigurableResponseProcessor<RESPONSE> createLoginResponseProcessor(InjectionPoint injectionPoint) {
        return super.createConfiguredResponseProcessor(injectionPoint);
    }

    @Override
    protected LoginConfigurableResponseProcessor<RESPONSE> getBaseResponseProcessor() { //<2>
        return CDI.current().select(LoginConfigurableResponseProcessor.class).get();
    }
}
----
<1> You need to create a producer (invoking `getConfiguredResponseProcessor` will provide you with a configured instance)
<2> Override the `getBaseResponseProcessor` method to return our type (this will be configured by `getConfiguredResponseProcessor`).

After this, you can use your own implementation, either alongside the default solution, even in a single test:

[source,java]
----
import hu.icellmobilsoft.roaster.restassured.response.producer.impl.ConfigurableResponseProcessor;

class ExampleTest {
    @Inject
    @RestProcessor(configKey = "testsuite.rest.exampleService.example")
    private LoginConfigurableResponseProcessor<ExampleResponse> loginResponseProcessor;

    @Inject
    @RestProcessor(
            configKey = "testsuite.rest.exampleService.example",
            expectedStatusCode = HttpStatus.SC_UNAUTHORIZED
    )
    private ConfigurableResponseProcessor<ExampleResponse> noLoginResponseProcessor;
}
----