= RestAssured

A RestAssured modul használatához csak be kell hivatkozni a pom.xml-ben

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-restassured</artifactId>
</dependency>
----

== RestAssured használata

A teszt fájlok a következő mintát követik:

[source,java]
----
@DisplayName("Testing XY service hu.icellmobilsoft.project.sample.service.rest.test.ISampleTestRest.postSampleRquest")
@Tag(TestSuiteGroup.RESTASSURED)
public class PostSampleRequestIT extends BaseConfigurableWeldIT {

    @Inject
    @ConfigProperty(name = "service.sample.uri")
    private String baseUri;

    @Inject
    @JSON
    private RequestSpecification requestSpecification;

    @Inject
    @JSON
    private ResponseSpecification responseSpecification;

    @ParameterizedTest
    @CsvSource({ "1, 1, 2", "2, 3, 5", })
    @ExplicitParamInjection
    void test(int a, int b, int expectedSum) {
      Assertions.assertEquals(expectedSum, a + b);
    }

    @Test
    @DisplayName("Testing opg generator json rest")
    void testSampleRest() {
        SampleRequest body = new SampleRequest();

        SampleResponse actual = RestAssured
                // given
                .given()//
                .spec(requestSpecification)//
                .config(restAssuredConfig).body(body) //
                .baseUri(baseUri) //
                // when
                .when()//
                .log().all()//
                .post("/sample")
                // then
                .then()//
                .log().all()//
                .spec(responseSpecification)//
                .extract().response().getBody().as(SampleResponse.class);
        Assertions.assertEquals(FunctionCodeType.OK, actual.getFuncCode());
    }
}
----

=== RestAssured default beállításai

Alapértelmezetten XML vagy JSON formátumra van támogatás a rendszerben.
A beállításokat a következő osztályok kezelik:

* RestAssuredConfigProducer
* RequestSpecificationProducer
* ResponseSpecificationProducer

Mind szabadon módosíthatóak az implementáló projekten.

==== JSON default beállításai

* A request content-type és accept "application/json".
* A response HTTP status 200 és "application/json" accept.
* A default beállításokat a Jackson2ObjectMapperFactoryImpl foglalja össze.

Ha igény van egy saját ObjectMapperConfig-ra,
mint ami a ObjectMapperConfigProducer-ben keletkezik,
akkor minta megoldásnak használható például:

[source,java]
----
@Inject
@JSON
private RestAssuredConfig restAssuredConfig;
 
((Jackson2ObjectMapperFactoryImpl) restAssuredConfig.getObjectMapperConfig().jackson2ObjectMapperFactory()).getObjectMapper()
        .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
----

==== XML default beállításai

* Kódolás UTF-8.
* A request content-type és accept "application/xml".
* A response HTTP status 200 és "application/xml" accept.


=== ResponseProcessor

==== Implementálása

Egy adott endpoint tesztelésének segítésére született meg a `ResponseProcessor` absztrakt osztály.
Leszármazástatáskor meg kell adni a Response típusát generikus paraméterben,
valamint implementálni kell 2 String-et visszaadó metódust, hogy az endpoint-ot azonosítsuk:

* `baseUriKey`: A Roaster konfigurációban használt kulcs, ami megadja az endpoint baseUri-jét
* `path`: Az endpoint path. Pl.: http://localhost/foo/bar esetén: /foo/bar

Opcionálisan az osztály többi metódusa is felülírható,
hogy a request-et vagy a response foldolgozását személyre szabhassuk.
Például a `createRequestSpecification` metódust felülírva
módosíthatjuk a request header-öket, sütiket, stb.

==== Használata

A `ResponseProcessor` implementáció `getJson`, `postJson`, `getXml`, `postXml` metódusait
használva tudjuk meghívni az endpoint-ot és automatán parse-olni a választ.

==== Példa

[source,java]
----
public class ExampleQueryResponseProcessor extends ResponseProcessor<ExampleQueryResponse> {

    @Override
    public String baseUriKey() {
        return "example-project.example-service.url"; // értéke pl.: http://localhost:8080
    }

    @Override
    public String path() {
        return "/example/foo/{id}";
    }

    @Override // Példa extra header hozzáadására
    protected RequestSpecification createRequestSpecification(RequestSpecification initRequestSpecification) {
        return super.createRequestSpecification(initRequestSpecification)
                .header("Authorization", "Basic dXNlcjpwYXNz");
    }

    public ExampleQueryResponse queryWithJson(String id) {
        return getJson(ExampleQueryResponse.class, id);
    }

    public ExampleQueryResponse queryWithXml(String id) {
        return getXml(ExampleQueryResponse.class, id);
    }
}
----

=== ConfigurableResponseProcessor

Annak érdekében, hogy ne kelljen minden rest végponthoz külön `ResponseProcessor`-t implementálni,
létrejött a `ConfigurableResponseProcessor` osztály, ami konfigurációból olvassa ki a szükséges értékeket
például a `baseUriKey`-t és a `path`-t.

==== Használata

A konfigurációban fel kell venni közös prefix alá a `baseUriKey`-t és a `path`-t.
Opcionálisan itt `headers` is megadható.
YAML formátum esetén ez így néz ki:

[source,yml]
----
testsuite:
    rest:
        exampleService:
            example:
                baseUriKey: example-project.example-service.url
                path: /rest/exampleService/example/{id}
            headerExample:
                baseUriKey: example-project.example-service.url
                path: /rest/exampleService/example/{id}
                headers:
                    - "X-LANGUAGE: hu"
                    - "User-Agent: roaster/0.5 restassured"
----

A tesztosztályba a `ConfigurableResponseProcessor`-t a `@RestProcessor`
qualifier-rel lehet inject-álni a konfig prefixet megadva:

[source,java]
----
import hu.icellmobilsoft.roaster.restassured.response.producer.impl.ConfigurableResponseProcessor;

class ExampleTest {
    @Inject
    @RestProcessor(configKey = "testsuite.rest.exampleService.example") //<1>
    private ConfigurableResponseProcessor<ExampleResponse> responseProcessor;

    @Inject
    @RestProcessor(
            configKey = "testsuite.rest.exampleService.example",
            expectedStatusCode = HttpStatus.SC_BAD_REQUEST //<2>
    )
    private ConfigurableResponseProcessor<ExampleResponse> badRequestResponseProcessor;

    void test() {
        responseProcessor.setQueryParams(Map.of("foo", "42")); //<3>
        ExampleResponse response = responseProcessor.getJson(ExampleResponse.class, "XXX");
        // asserts...
    }
}
----
<1> Alap `ConfigurableResponseProcessor` inject példa
<2> Opcionálisan az elvárt válasz státusz kód is megadható az annotációban (default: `200 OK`)
<3> `ConfigurableResponseProcessor`-ban a query paramétereket is meg lehet adni

==== Saját implementáció

Ha az adott projekten belül ki szeretnénk egészíteni a `ConfigurableResponseProcessor` működését
(pl: login, vagy egyéb projekt specifikus header kezeléshez),
azt első lépésben az `AbstractConfigurableResponseProcessor` implementálásával tehetjük meg:

[source,java]
----
import hu.icellmobilsoft.roaster.restassured.response.producer.spi.AbstractConfigurableResponseProcessor;

@Dependent
public class LoginConfigurableResponseProcessor<RESPONSE> extends AbstractConfigurableResponseProcessor<RESPONSE> {
    @Inject
    private LoginHandler loginHandler;

    @Override
    protected RequestSpecification createRequestSpecification(RequestSpecification initRequestSpecification) {
        loginHandler.login();
        return super.createRequestSpecification(initRequestSpecification)
                .headers(loginHandler.loginHeaders());
    }
}
----

Ezek után egy CDI producer-t kell létrehozni, ami kiszolgálja a konfigurált példányokat:

[source,java]
----
import hu.icellmobilsoft.roaster.restassured.response.producer.spi.AbstractConfigurableResponseProcessorProducer;

@Dependent
public class LoginConfigurableResponseProcessorProducer<RESPONSE> extends AbstractConfigurableResponseProcessorProducer<LoginConfigurableResponseProcessor<RESPONSE>> {
    @Override
    @Produces //<1>
    @RestProcessor(configKey = "")
    public LoginConfigurableResponseProcessor<RESPONSE> createLoginResponseProcessor(InjectionPoint injectionPoint) {
        return super.createConfiguredResponseProcessor(injectionPoint);
    }

    @Override
    protected LoginConfigurableResponseProcessor<RESPONSE> getBaseResponseProcessor() { //<2>
        return CDI.current().select(LoginConfigurableResponseProcessor.class).get();
    }
}
----
<1> Létre kell hozni egy producer-t (a `getConfiguredResponseProcessor`-t meghívva már egy bekonfigurált példányt kapunk)
<2> Felül kell írni a `getBaseResponseProcessor`-t, hogy a mi típusunkat adja vissza (ezt fogja a `getConfiguredResponseProcessor` konfigurálni)

Ez után már használhatjuk is a saját impelmentációnkat, akár a default megoldással együtt, egy tesztben is:

[source,java]
----
import hu.icellmobilsoft.roaster.restassured.response.producer.impl.ConfigurableResponseProcessor;

class ExampleTest {
    @Inject
    @RestProcessor(configKey = "testsuite.rest.exampleService.example")
    private LoginConfigurableResponseProcessor<ExampleResponse> loginResponseProcessor;

    @Inject
    @RestProcessor(
            configKey = "testsuite.rest.exampleService.example",
            expectedStatusCode = HttpStatus.SC_UNAUTHORIZED
    )
    private ConfigurableResponseProcessor<ExampleResponse> noLoginResponseProcessor;
}
----