= Oracle DB

To use the Oracle DB module, you just need to reference it in the pom.xml file

[source,xml]
.pom.xml
----
<dependency>
    <groupId>hu.icellmobilsoft.roaster</groupId>
    <artifactId>roaster-oracle</artifactId>
</dependency>
----

== Oracle DB configuration parameters

With MicroProfile Config, the necessary data for accessing Oracle DB can be parameterized.

Examples:

[source,properties]
.META-INF/microprofile-config.properties
----
roaster.datasource.oracle.application.url=jdbc:oracle:thin:@//oracle.icellmobilsoft.hu:1521/sample
roaster.datasource.oracle.application.user=db_user
roaster.datasource.oracle.application.password=db_pass
----

[source,yml]
.META-INF/roaster-defaults.yml
----
roaster:
    datasource:
        oracle:
            application:
                url: jdbc:oracle:thin:@//oracle.icellmobilsoft.hu:1521/sample
                user: db_user
                password: db_pass
                maximumPoolSize: 10 #<1>
----
<1> (Optional) The maximum value of the connection pool (default: 5)

== Using OracleJDBCSelectorService

First, you need to inject the service class.

[source,java]
.Injecting OracleJDBCSelectorService
----
    @Inject
    @DBConnection(configKey = DBConstants.Schema.APPLICATION)
    private OracleJDBCSelectorService service;
----

=== Operations of OracleJDBCSelectorService

Through OracleJDBCSelectorService, operations can be accessed. When these operations are invoked and if there is no open connection yet, it creates a new one with the database. At the end of the operation, it closes the connection.

IMPORTANT: Methods starting with "select" accept only SQL statements that begin with "SELECT"!
The `selectFirst` method returns only the first row if there are multiple results from the database.

* selectFirstStringValue(sql select string, columnName)
* selectFirstIntegerValue(sql select string, columnName)
* selectFirstBooleanValue(sql select string, columnName)
* selectFirstBigDecimalValue(sql select string, columnName)
* selectFirstDateValue(sql select string, columnName)
* selectRowCount(sql select string)
* selectFirstObject(sql select string, converter)
* selectAllObjects(sql select string, converter)

[source,java]
.Examples of operation calls
----
String name = service.selectFirstStringValue("SELECT * FROM EXAMPLE WHERE X__ID = '0'", "NAME");
int rowCount = service.selectRowCount("SELECT * FROM EXAMPLE WHERE X__ID = '0'");
List<Example> exampleList = service.selectAllObjects("SELECT * FROM EXAMPLE", exampleConverter::convert);
----

[source,java]
.Examples of Converter
----
private T convert(ResultSet rs) throws BaseException {
    try {
        T t = new T();
        t.setId(rs.getString("X__ID"));
        t.setName(rs.getString("NAME"));
        return t;
    } catch (SQLException e) {
        throw new TechnicalException(e.getLocalizedMessage());
    }
}
----

=== Methods necessary for managing connections

* getJdbcConnection()
* setJdbcConnection(JDBCConnection)
* close